### ISSUE TITLE
chacontrol not blocking spam with spaces

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1018]
Is not blocking for example "mc illimited eu"
My config https://gist.github.com/xion87/66cc4a67fda89e546d56a3e4301980ec

**Comment by jascotty2** [comment]
The reason is that the config you have is not looking for spaces as potential url delimiters - it's looking for `(\.|dot|\(dot\)|-|;|\*|\_|:|,)` - an easy way to fix this to do what you're looking for is to add a `?` to the end of that grouping, like this:
`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|\*|\_|:|,)?\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|e(| +)u|i(| +)t|g(| +)s|s(| +)e(| +)r(| +)v|n(| +)u|u(| +)s|m(| +)l|n(| +)l|d(| +)e)\b`

Note, however, that this could give you false positives if someone starts talking about the eu in chat
