### ISSUE TITLE
Chc color issues

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1020]
Following #998, I was testing the new chc and I found a 2 issues + have 2 request.

**Issues:**
1) outdated gui https://gyazo.com/17c11cb76402c8fd49de8764d8df73c2 doesn't mention anything about gui permissions e.g. `chatcontrol.commands.color.gui.red`
2) player with only `chatcontrol.commands.color.gui.red` will not see that anything in /chc color except for the barrier block.

**Feature Request:**
1) Can you please make it so there is a permission to even open the gui. It is a must.
2) Can you also make /chatcolor and /chatcolour default commands like /tell and /r, people shouldnt need to type /chc colour to get to the gui.

**Comment by kangarko** [comment]
@jascotty2 or I will take this until 23th December, thank you

**Comment by kangarko** [comment]
Hey, sorry we did not catch up in time, I had to prioritize bug fixes.

Issues:
1 and 2. _I have to read myself up on the changes_ @jascotty2 since you edited the changes please take a look

Feature requests:
1. Give players negative chatcontrol.commands.color permission to prevent them from accessing the color menu.
2. Please see https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands

**Comment by LogGits** [comment]
Any news on this.

**Comment by kangarko** [comment]
I am checking up with Jacob on this. Apologies for the delay.

**Comment by jascotty2** [comment]
After some discussion, the color system was modified again in a form that may better benefit your needs:

Players that have the `chatcontrol.commands.color.gui` permission or the earlier group option will have the gui menu color nodes changed to the `chatcontrol.commands.color.gui.{color}` nodes, instead of the last implementation that uses an exclusion method.

In the release 7.11.9, if you have the `chatcontrol.commands.color.gui` permission assigned to a player, the only colors that will be selectable in the `/chc color` menu will be colors that are assigned corresponding to `chatcontrol.commands.color.gui.{color}` - these may be completely different to the `chatcontrol.chat.format.color.{color}` permissions the player may have.

**Comment by kangarko** [comment]
Thank you Jacob! I will push the changes within 36 hours.
