### ISSUE TITLE
Sound Notify - Only Highlight for Mentioned Player

### ISSUE THREAD

**Issue by fjeddy** [kangarko/ChatControl-Pro#1083]
When a player is mentioned, the color set is displayed for every single user online, it defeats the entire purpose of the highlight if you are going to highlight the usernames for every player every time.

I bought this plugin specifically for the "highlight with color" feature, and it doesn't work at all as expected. It's truly not highlighting anything when it's highlighting everyone for everyone, you still have to read it to know it's for you, instead of just knowing that the color automatically means that your nickname is in it.

**Comment by kangarko** [comment]
How do you want the feature to function?

**Comment by fjeddy** [comment]
The name should ONLY be highlighted for the person who owns the name, no one else. If my name in-game is "abc" and someone else is called "cba", then the name should only be yellow for me when "abc" is mentioned.

But right now, "abc" and "cba" will get yellow names for both "abc" and "cba". You have no clue if someone actually mentions you, because every name is yellow, so you still have to read the names.

**Comment by kangarko** [comment]
I have reviewed the system. Short answer - currently not possible. Long answer: When you send a message, it is constructed once (all variables parsed etc.), and this message is sent to all players. If we would have to construct the message for each player, it would be very expensive on your machine because it requires thousands of combinations of variables to be compiled.

I understand the limitations of this system and have noted this down. Will keep this open so it serves as a reminder for a future change.

I can look into changing the entire message to a certain color, however that would render it to every other player on the server as well.

PS: The color works for me, what's your Sound_Notify in settings.yml?
![a](https://i.imgur.com/7ZSEGP4.png)

**Comment by fjeddy** [comment]
Like I said, the color works and is displayed 9 out of 10 times. But that's not what a "Color notification" and "Color highlight is", your entire sales pitch, argument and configuration is incorrect, I bought this plugin specifically to highlight the message for ONLY the player who is mentioned, it's completely, utterely, 100% pointless to highlight the name for absolutely everyone on the server.

A chargeback will now be claimed, as this is not only a useless plugin (For me), it's also false advertising and a product that's faulty based on it's description. But more importantly, the time you have made me waste on this.

**Comment by kangarko** [comment]
The system will remain, your attitude deserves no help.
