### ISSUE TITLE
rule dosen't work in korean lang

### ISSUE THREAD

**Issue by djacks6278** [kangarko/ChatControl-Pro#1138]
match 욕설
then replace 욕설은 나빠요.

it's rule text line
and trying chat 욕설
but didn't work

match bad
then replace 욕설은 나빠요.

and this one
is perfect work

u write the support other lang
but didn't work..
regex checker is can find 욕설 and no wrong in rule
plugin dosen't supoort other lang? only eng? really?

**Comment by kangarko** [comment]
Hello and thanks for using our plugin!

Normally all languages are supported but there may be edge cases for non-latin alphabets. Unfortunately there is nothing we can do about it since the technology we use is not coded in ChatControl.

You can try setting **Regex_Strip_Colors** to **false**, also **Translate_Diacritical_Marks** to **false** and also **Anti_Spam.Similarity_Check.Ignore_Special_Characters** to **false**, all in settings.yml file. Restart your server and see if that makes it work.

Hope that helps,
Have a wonderful day!
