### ISSUE TITLE
[Feature Request] Toggleable chat filter

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#1151]
Exactly like the title says. For example, certain players with the toggle on would see all uncensored text from a certain file (for example rules.txt), and players with the toggle off would see normal censored chat.

A way you could do this is for players with the toggle on to bypass the handlers, while the players with the toggle off would see chat without the handlers.

This feature is on Hypixel chat. It is very useful.

Thanks for reading!

**Comment by kangarko** [comment]
Hello,

I believe we already have such feature. Please take a look at the following Wiki article: https://github.com/kangarko/ChatControl-Pro/wiki/Chat-Ignorers

I am closing this ticket because I assume that this feature is the one you were looking for. If not, please comment below.

Sincerely,
Matej
