### ISSUE TITLE
Hide Channel Join Text

### ISSUE THREAD

**Issue by Funreal** [kangarko/ChatControl-Pro#116]
Unable to hide text "Player (PLAYER) has joined this channel (CHANNEL)" in chat.
**Chat.Channels.Notify_On_Join: false** doesn't hide it. (only sometimes what I have noticed)

**Stacktrace?** https://pastebin.com/CtNe7anH

**Comment by kangarko** [comment]
Hello,

the key that is fetched from the config is hardcoded in the join event. It will either function, or not. The only reason I see why it's sometimes not working is because of server reload or any use of a sort of plugin reloader. If you are using PlugMan or similar, this might also cause the stacktrace.

**Comment by Funreal** [comment]
Removed PlugMan, that got rid of the Stacktrace.
The message when a player joins the server/channel does still show up though.

**Comment by kangarko** [comment]
Post me your settings.yml please, so I can test it out exactly as it appears on your server.

**Comment by Funreal** [comment]
Almost default.
https://pastebin.com/SL02ZUN6

**Comment by kangarko** [comment]
Sorry, I could not reproduce it. To me it works, also the message is hidden if the option **Chat.Channels.Notify_On_Join** is set to false.

You can try this fall-safe method: Create a the file localization/messages_en.yml (change en for any other language you are using), restart the server, let the file be filled with keys, and set the **Channels.Notify_Channel** to **"none"** in that file.

**Comment by Funreal** [comment]
Reproduce: 
Have one account online. Login with the 2nd account, then check the 1st accounts chat.

**Comment by kangarko** [comment]
I still cannot reproduce, sorry. Please ensure you are on the latest version, and no PlugMan or similar was used to (re)load the plugin. Anyway, if the second account joins, the first will not receive any message, because the message about which channel the player is in, is only sent to the player who joined, not anyone else.

Does the second solution with localization work?

**Comment by kangarko** [comment]
Please comment below if still having issues.
