### ISSUE TITLE
Vault didn't find any chat plugin

### ISSUE THREAD

**Issue by Yann151924** [kangarko/ChatControl-Pro#119]
When i launch a server with chatcontrol and vault i have this error :

`2016-11-08 11:09:49 | *-----------------------------------------------*
2016-11-08 11:09:49 | You enabled Chat formatter,
2016-11-08 11:09:49 | but Vault didn't find any
2016-11-08 11:09:49 | chat plugin! Run /vault-info
2016-11-08 11:09:49 | and check what is missing
2016-11-08 11:09:49 | Plugin is now disabled.
2016-11-08 11:09:49 | *-----------------------------------------------*`

And /vault-info say that :

![image](https://cloud.githubusercontent.com/assets/7802164/20095570/4e2470c0-a5a6-11e6-9c19-6430e39a9939.png)

I try without luckperms it's the same error. I don't know if the problem is a misconfiguration or come from our plugin.

Server version : thermos 57 (1.7.10 Forge 1614)
Plugin : chatcontrol 7.0.28, vault last version, luckperms 2.13.48

**Comment by DJDan193** [comment]
PermissionsEx works fine. https://dev.bukkit.org/bukkit-plugins/permissionsex/

**Comment by Yann151924** [comment]
@DJDan193 that's not the point, if i remove luckperms it will no work

**Comment by DJDan193** [comment]
What won't work? I have the same error and adding permissionex worked

**Comment by Yann151924** [comment]
Yes but luckperms is my permissions plugin :( .

For testing i add permissionsex it work like a charm with no problem, so i presume the problem coming from Luckperms, i'll report to the dev of Luckperms.

I'm going to let the issue open if the dev have an idea where the bug come from ?

**Comment by Yann151924** [comment]
Solution : 
The plugin luckperms need to be load before Chatcontrol so the dev of Luckperms say to me to put LuckPerms in soft-depend in plugin.yml, this don't work chatcontrol already loaded before luckperms but when i put LuckPerms in depend the plugin is loaded after Luckperms.
It's work but if @kangarko can make a workaround for the next version it can be really great :)

**Comment by kangarko** [comment]
Hello,

ChatControl relies on Vault and uses its methods to fetch relevant variables. If Vault does not support LuckPerms, it won't work.

So putting LuckPerms in soft-depend solved this issue? If so, I can integrate this line into the next version for convenience.

**Comment by Yann151924** [comment]
LuckPerms just need to be load before chatcontrol :), but when i put in soft-depend it not work LuckPerms is not loaded before :(. In contrary when i put it in depend LuckPerms is loaded before don't know why

**Comment by lucko** [comment]
Hi kangarko, LuckPerms author here.

This is a sadly just an issue with the Bukkit (soft)depend system - not really anything you're doing wrong. The best way to solve the problem, without just soft depending on every permissions plugin in existence (which is what I assume you're doing currently) is to:

1: Listen for https://jd.bukkit.org/org/bukkit/event/server/ServiceRegisterEvent.html. Just update your internal instance of Vault's Permission/Chat interfaces when they get provided by new service providers.

2: If you want to check if a provider is present when the server starts, do that in a 1 tick delayed task. The scheduler only starts when all other plugins are enabled - so you can check at a slight delay, instead of soft-depending on lots of permission plugins.

Depending on Vault alone won't work, permission plugins have to do that too. :)

**Comment by kangarko** [comment]
Hey lucko,

thank you for your collaboration. ChatControl uses own system to detect whether Vault has hooked into a chat- or economy-providing plugin. I have moved this check after all plugins are loaded and the issues seems now to be gone.
