### ISSUE TITLE
Feature Request: proximity chat command

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1206]
We have the option to have global chat or proximity chat, I always have global chat on, but as proximity chat exists, could we please have a command to just talk in proximity chat even if global is on? sometimes people have times they want to talk to just the people near them without being in the same channel/crew.

Thanks.

**Comment by kangarko** [comment]
Hi,

sure, have you looked at the Commands option in channels.yml?

![a](https://i.imgur.com/TEp17dj.png)

**Comment by FrozenBeard** [comment]
oh, so If I created a Channel I could set it to ranged? I have channels disabled due to how it handles the global chat as its own channel people can leave/not auto entered into it.

**Comment by kangarko** [comment]
Yes, each channel can be ranged and behave like a ranged chat, see our Channels wiki page

**Comment by gelsbern** [comment]
How I accomplished this was to create a channel called local, that everyone joins automatically in write mode.  The other channels I set up where they join in read mode only. Then I set up a bunch of aliases to do /channel send <channelname>  like /shout = /channel send global $1- .  What this accomplished is that when they just type, it ends up going to the ranged channel since that's the only they are joined to in write mode and if they want to chat in global chat, they type /shout  in front of their message.
