### ISSUE TITLE
Suggestion: Revamp the Broadcaster

### ISSUE THREAD

**Issue by delbertina** [kangarko/ChatControl-Pro#1213]
This might be something that is already possible, but I cannot find any documentation on how to do so thus this suggestion.

-----------------------
Suggestions:
- Groups of messages that can be either enabled or disabled
- Permission based message sets
- Move broadcaster to its own file
- Better error fallback 
- Command to add / edit broadcaster messages in-game
- Log file for when broadcast msgs were shown

---------------------
**Groups of messages** would be helpful for keeping messages around in the file without being in a comment that gets deleted with config updates. I've run into this issue when having recurring seasonal messages. It might look something like this ...

```yaml
Messages:
  global:
    group1:
      Enabled: false
      Messages:
      - Holiday message 1
      - Holiday message 2
    group2:
      Enabled: true
      Messages:
      - Evergreen message 1
      - Evergreen message 2
```

**Permission based message** sets would be useful for sending messages on a grey-list type server as well as just a general newbie vs veteran situation. Maybe the config would have a place to set the permission for a set and priority value to determine the set to show a player. 

With these two suggestions potentially complicating the config section, it might help to also **move this feature to its own config file**. 

Along with this, it would be nice to have **better error fallback** especially for this feature. I find myself editing it a lot and even with a yaml parser I still mess up a few times and have the whole plugin go down. I've seen some plugins able to just disabled a feature temp if a config errors on load etc. I realize that it might not be possible with how you setup your plugin, but if it is possible that would make my day.

Down the same alley as error fallback, having a **command in-game to edit** the broadcaster messages would also reduce error. The most memorable plugin that I've seen do this type of editing well is CMI. I know this type of feature is probably a lot of work and time so kinda just throwing it out there.

It might end up being redundant for most and way underused overall, but would be nice to have the option of **logging to a file** when broadcast messages are shown. 

----------------
Really like this plugin and have been using it for years so just looking to maybe help make it better. : )

**Comment by kangarko** [comment]
Thank you. Honestly we are more busy than ever this year so really no promises, I'll start by taking the suggestions from last year and then I'll take a look.

**Comment by kangarko** [comment]
Pulled to roadmap

**Comment by FrozenBeard** [comment]
+1 for a better broadcaster!
I am still using AutoMessage which hasnt been updated since 2016 and its got many more features including grouping:
https://dev.bukkit.org/projects/automessage

The biggest thing will be moving it to its own file, IMO all things like MOTD and Announcements need their own files, its so messy having everything in one giant file.

Things to add to this re-work:

1. Timed messages, I will have offers on for X amount of time to auto stop broardcasting messages
2. Toggles for specific messages, for example I have donator messages to tell them they have XYZ, they will learn this after time and will want to toggle just that set of messages, but NOT the global ones! I dont want someone to be able to toggle global messages.
3. Have a variable to center text, having to try and figure out spacing to center text is horrible, but it makes all the difference for messages not getting lost in all the other chat.
4. Make sure there is a new line break \n or {break} or something, white-space is always forgotten when making things like this, so important to have white space break up messages.
5. Support for announcements to be hotbar, title or even better pop up in a book messages not just chat!
6. Per-world broadcasts.
7. Multi line broadcasts

Already supports placeholderAPI right?

Here some screenshots for pre-made formats you could use as examples for people (Go down to screenshots)
https://www.spigotmc.org/resources/%E2%99%A6-kixs-auto-announcer-%E2%99%A6-multi-line-permissions-auto-center-in-game-editor-1-8-1-14-4.68425/

**Comment by kangarko** [comment]
Thanks for your feedback!
