### ISSUE TITLE
Permission Based Formatting Help

### ISSUE THREAD

**Issue by EnderGamingFilms** [kangarko/ChatControl-Pro#1242]
Hello! I've searched through a few issues for an answer (not all of them) but couldnt find one that really helped. I was wondering how I could have permission based chat formats. 

The default is set to "Chat" and thats fine and setup for my server, but I was using DeluxeChat previously and I gave donators, staff, admins, and owners different chat formats. Is it possible to make a new format in the formattting.yml file and then give a permission like "chatformat.admin" to people through LuckyPerms to allow them to use that chat format instead of the default "Chat"?

Old Config (DelxeChat): https://pastebin.com/eFdSqcQH

Note: Running Latest, and 1.13.2 Paper-Spigot.

**Comment by kangarko** [comment]
Hey,

yes, definitely, you may want to look into Groups (https://github.com/kangarko/ChatControl-Pro/wiki/Groups#chat_format). Just make sure you enable them in settings.yml and configure according to that article (or see our default settings.yml also in the Wiki).

Matej

**Comment by EnderGamingFilms** [comment]
Sorry, but I don't really understand how it works still.

settings.yml
https://pastebin.com/X12gg8kE

formatting.yml
https://pastebin.com/QYsMhbCz

In-game:
https://imgur.com/w7gW0qw.png

**Comment by kangarko** [comment]
First of all, remove the default key, it will cause issues and you do not need it. If the user does not have any group permission they use the chat format you defined in formatting.yml in Formats.Chat.

Your formatting.yml file has est2 instead of test2 name, correct that typo and try again.

Also try restarting your server when you give yourself chatcontrol.groups.pro permission, LuckPerms changes are sometimes not reflected instantly in ChatControl.

**Comment by EnderGamingFilms** [comment]
Settings:
https://pastebin.com/itTaM4H0

Formatting:
https://pastebin.com/QHeiVD8S

In-Game (restarted server):
https://imgur.com/RKsVRxm.png

It still isn't working. I gave the "pro" rank chattcontrol.groups.pro also the default rank is using that chat preset as well but does not have the permission...

**Comment by EnderGamingFilms** [comment]
Ok, I think this might work. I did " lp group pro permission set chatcontrol.group.default false" and pro uses the correct format now, but why not have a priority flag so that the formats don't clash with eachother? Like for every rank I have to deny/allow every format I have since they are all apart of an inheritence tree. It would really be nice to add that flag, and I can't really see why it wasn't in to begin with.

**Comment by EnderGamingFilms** [comment]
I set everything up and I added all the proper permissions and denied all the upper formats. But when I use "lp user EnderGamingFilms parent add Pro" it does not use the donator chat format it just used the default one.

Image (It works with lp user [user] parent set, but not with parent add):
https://imgur.com/8RSpX01

**Comment by kangarko** [comment]
Hi, silly question but have you tried restarting the server? I mentioned that when you do /lp user command it may or may not update in ChatControl automatically.

**Comment by EnderGamingFilms** [comment]
Yeah I said above that I was restarting the server. (I do it everytime I make a change)

**Comment by kangarko** [comment]
I am afraid that's something in the LuckPerms plugin, if your inheritance is correct and you are negating parent permissions so that you only have 1 group permission per LuckPerms group, than I honestly don't know, perhaps you could ask on their Issues Channel on how their inheritance work. Thanks and sorry about that.

**Comment by EnderGamingFilms** [comment]
Ok, it's probably my inheritance I'm only using parents for groups.
