### ISSUE TITLE
Getting killer prefix in death messages?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#1266]
Hello! I am trying to customize my death messages file. I want the PVP death messages to show the victim's and killer's  LuckPerms group prefixes. I am able to get the victim's prefix to work correctly, but I cannot figure out how I would go get the killer's prefix, even after looking through the wiki several times.

**Comment by kangarko** [comment]
Hey,

seems I have bad news for you, at present it's not possible to use anything else besides the killer's name as his placeholder. This is because there's only one {player_X} variable in PAPI and so it would override the player's variable. This is a cycle and it appears my hands are tied in this very case. My sincere apology for this.

Matej

**Comment by PsychoLynx** [comment]
Thank you kindly for letting me know!
