### ISSUE TITLE
3 Simple questions.

### ISSUE THREAD

**Issue by NobleStrike** [kangarko/ChatControl-Pro#1330]
I'm trying to convert from the essentials chat prefix system that I've used for 6 years to your cutting edge chat plugin. After thoroughly reading over your tutorial for a few days I'm struggling to understand a few things. Let me start with the simple question.

1. I understand the bungee server has its own plugin to hook into the other servers. Does every server require the full chat control plugin to be installed to hook? Does it select only one host server configs to apply to the rest of the servers? Or is each independent entirely?

2. Does chat control have a prefix system for ranks? When I set the formatting to include {prefix} it just says ChatControl in chat in its place. I was wondering if the plugin has lightweight prefix system that would use the default formatting group with a variable that would throw in the users group name as the prefix.

3. How do I add more than one chat format for other groups? I assume this is how I would manage prefixes and chat colors per rank and such through chatcontrol entirely? I set the default group to chat like your guide says if I want to enable it, which worked fine for the first default rank. I used pex to give myself the default vip group perm. ChatControl does see me as a vip when I hover over my own messages. Then I attempted to add vip group to the format.yml and failed pretty bad. I have 23 ranks to setup for my main server, but just testing it out with the vip group until I understand it.

Here is my config https://pastebin.com/yt9f58kt

Running spigot 1.14.4, chatcontrol pro 8.3.7, Vault 1.7.2, ProtocolLib 4.4.0 I have not hooked into bungie yet.

Thank you for your hard work and help.

**Comment by kangarko** [comment]
Hello,

congratulations on making that shift. I remember when I was using PermissionsEx with Essentials to format the chat in 2012 and that was a tougher.

1. Yes, install CCP on all Bukkit-based servers (Spigot, PaperSpigot) and BungeeControl on BungeeCord. You obtained an unlimited licence under a single BungeeCord network for that.

2. Two best options here. You can either install Vault to pull your prefix from your permissions plugin such as LuckPerm and then use {pl_prefix} variable instead, or create dynamic chat format part in formatting.yml with the "Sender_Permission" that will only display the particular format part when the sender has that permission, supplying as a prefix.

3. I am not sure if I understood you correctly but you could just use the Sender_Permission key (just write it) in your "vip group" (we call that format part) in formatting.yml so that is only displayed when users have certain perm.

**Comment by NobleStrike** [comment]
"or create dynamic chat format part in formatting.yml with the "Sender_Permission" that will only display the particular format part when the sender has that permission, supplying as a prefix."

This is my goal. Do you have a example formatting.yml of this? Once I know what it should look like I should be able to finally swap over. Thank you for the help and I apologize for asking so much.

**Comment by kangarko** [comment]
We did not, but I wrote a small copy for you:

https://github.com/kangarko/ChatControl-Pro/wiki/Formats#conditional-format

Hope that helps!
