### ISSUE TITLE
Chat priorities

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1362]
When people use /pc or /ac from McMMO to turn on those chats, the messages will be sent to the normal chat instead. Same for when i'm in vanish using PremiumVanish, when I sent something in the chat it is suppose to block the message from sending, but that doesn't happen.

What should I do?

`Listener_Priority:
  Checker: NORMAL
  Formatter: HIGH
  Signs: HIGHEST`

**Comment by kangarko** [comment]
Have you tried changing the formatter priority to HIGHEST? I believe than you'd have to change checker to MONITOR, that's not recommended but can be done

**Comment by Sikatsu** [comment]
It used to be on HIGHEST and it didn't work. So I changed it to HIGH, but still premiumvanish doesn't block the message from sending and there is no way to toggle admin or party chat from mcmmo, as it will just get sent in the normal chat instead.

**Comment by kangarko** [comment]
Hmm seems like we have an incompatibility situation here. The desired flow or priorities should be like this:

1. PremiumVanish - can player chat? Yes, pass through (lowest priority)
2. mcMMO - handle admin chat, else pass through (normal priority)
3. ChatControl Pro - take what's remaining (highest priority)

The problem is that the other plugin priorities' may not align with that pipeline. ChatControl offers you to change priority but that may not be enough.

You can try removing PremiumVanish to test if mcMMO + ChatControl on HIGHEST or MONITOR will work. If it does then it's unfortunately a poor priority in PremiumVanish and we're not able to fix it.

**Comment by Sikatsu** [comment]
PremiumVanish does have options for priority aswell. For cancellation it's set to HIGH, I tried setting it to different ones aswell without success.

Using /ac <text> or /pc <text> from mcmmo works, but the toggle to keep talking in a certain chat doesn't.

Tried it with all priorities really, can't get it to work somehow.

**Comment by kangarko** [comment]
Seems like mcMMO is the problem then, not really sure what to do here since we're trying to maneuver between three different plugins listening to the same, I apology I am not able to help.

Can you test using two plugins only? PremiumVanish on LOW and ChatControl on NORMAL.

Or eventually PremiumVanish on LOWEST, leave mcMMO as it as and ChatControl on HIGHEST? I know you wrote you tried something like this but just to confirm this exact combination won't work.

**Comment by kangarko** [comment]
If you're using channels.yml post me that file.

**Comment by Sikatsu** [comment]
Without McMMO: http://prntscr.com/oykczs

Premiumvanish is still not able to block the message from sending.

I don't use channels.yml sadly, just the bungee chat. It's also since then that this started to occur.

**Comment by kangarko** [comment]
Oh I see, for bungeechat if you have it set by default (i.e. you type a normal message, not a command)it then uses the Checker priority - have you tried to play around with that?

**Comment by Sikatsu** [comment]
What would you recommend? It's currently on NORMAL

**Comment by kangarko** [comment]
I have no idea, try all from LOWEST to MONITOR at this point...

**Comment by Sikatsu** [comment]
This issue was fixed.

**Comment by kangarko** [comment]
Mind sharing how did you solve it? I am going to add it to the Wiki for others as well

**Comment by Sikatsu** [comment]
Oops sorry, I set the CHECKER priority to HIGHEST.

**Comment by Sikatsu** [comment]
@kangarko Setting the checker priority to HIGHEST: https://pastebin.com/V9yyVBMs
