### ISSUE TITLE
ChatControl::Event: o.m.c.f.n. .A (PlayerQuitEvent) performance issue through BanManager

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1375]
ChatControl::Event: o.m.c.f.n. .A (PlayerQuitEvent) is apparently causing issue with BanManager, im not sure which plugin is causing this, so ive reported it to both.

![Screenshot 2019-08-26 22 54 36](https://user-images.githubusercontent.com/144046/63726331-e23d7f80-c854-11e9-939e-b9b59a6d9981.png)

**Comment by kangarko** [comment]
Using the latest version?

**Comment by kangarko** [comment]
Closing, we changed the join event multiple times now so it's essential you have the latest version.

The issue comes down to this: The MySQL connection takes about 100-500ms and we run it on the main thread for safety. I tried to run it async but it caused severe issues so that's why you can see the hang ups.

If ChatControl is rewritten from scratch I'm going to architecture the system around this completely

**Comment by FrozenBeard** [comment]
MySQL is 127.0.0.1, it should be instant.

**Comment by kangarko** [comment]
PM'd you on SpigotMC
