### ISSUE TITLE
[1.14.4-paper] - ChatControl bypassing personal mutes

### ISSUE THREAD

**Issue by darkjoya** [kangarko/ChatControl-Pro#1402]
ChatControl Version: 8.3.17
Server: paper-1.14.4 #build 186

Issue:
When i tried to mute someone my punishment plugin AdvancedBans says its done, but that muted player still writing chat. First i opened a issue in AdvancedBans git and they said remove all plugins and try it again. Well i did this and mutes works perfect. Then i start tried other plugins one by one and when i install chatcontrol again mutes start not working again. There is no errors in console.

ChatControl File:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3626345/ChatControl.zip)

**Comment by kangarko** [comment]
Hello,

this is likely caused by that ChatControl listens to the chat before AdvancedBans and does not see that the chat event has been cancelled. Please read and change your formatter priority to HIGH or HIGHEST according to https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

If that does not help, try other values, if these don't help either then it's very unfortunate but it's a major incompatibility.
