### ISSUE TITLE
Updater hang server loading.

### ISSUE THREAD

**Issue by sync667** [kangarko/ChatControl-Pro#150]
Hi i use latest version of ChatControl and spigot. It's not much important why updater can't connect, but plugin settings timeout to connect is to long and hang server startup. About 2-3 minutes? 

ChatControl Update check might failed due to ConnectException: Przekroczony czas oczekiwania na połączenie (Connection timed out)

You should make it like 30-60 seconds, maybe add poper info for user in console and settings in file to set limit self.

**Comment by Joannou1** [comment]
@kangarko 
[Fiddler] The connection to 'chatcontrol.6f.sk (88.86.120.160:80)' failed. Error: TimedOut (0x274c).

http://chatcontrol.6f.sk/check.txt
http://chatcontrol.6f.sk/note.txt

**Comment by sync667** [comment]
@kangarko one more thing how to preform alias so rule string for execute player command?

**Comment by kangarko** [comment]
Make sure your firewall allow connections on port 80 and to that update server address.

What plugin are you using to get the message: [Fiddler] [...] ?

@sync667 What do you mean? If you want a rule to execute a command, use 'then console' operator.

**Comment by kangarko** [comment]
Hello, I am aware of the issue. I just received an answer from my hosting provider. They have been facing a ddos attack during the weekend. They clam to have fixex the problem, and I was successfully able to connect to the update server. Please remind me if it occurs again.

**Comment by sync667** [comment]
I mean how to add rule so it will work like command alias?

**Comment by Joannou1** [comment]
Alright cool, I temporarily modified my hosts file to get around the issue last couple days.
Fiddler is a neat program that allows you to debug web traffic.
http://www.telerik.com/fiddler

Used this launch parameter on the server to route the traffic to fiddler: 
 -DproxySet=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888

**Comment by Joannou1** [comment]
It's also worth noting that the note.txt and check.txt are showing a 403 error page.

"403 - Přístup odepřen

Zkontrolujte, zda je na FTP nahraný index.php nebo index.html.
Je možné, že je Vaše IP adresa blokována kvůli podezření na šíření SPAMu. 
V případě dalších dotazů se prosím obraťte fórum podpory."

![6a982](https://cloud.githubusercontent.com/assets/997747/22446455/a0ea9018-e701-11e6-81df-9f9c0ec96b4b.png)

**Comment by kangarko** [comment]
Thank you very much for the information on Fiddler. ChatControl uses own user agent and other credentials to connect to the server, and all other connections are disallowed, thus rendering the 403 page. The first file contains developer message, for example when I am on holidays and there is something important to announce. To check the system out, install the free version and you'll see a message when the server loads. This is toggleable. The second file is a simple attempt to lower piracy. The files are in order, it was a connectivity problem due to my hosting enduring a ddos attack.

Btw, @sync667, please see the ChatControl's Wikipedia on creating command aliases, in most cases you don't need any rule.

**Comment by kangarko** [comment]
Closing, please remind me if any questions.
