### ISSUE TITLE
Players can /ignore staff

### ISSUE THREAD

**Issue by Teriuihi** [kangarko/ChatControl-Pro#1644]
Is there a way to allow staff members to fully bypass being ignored. Currently, they can still send messages to the player if they have chatcontrol.bypass.ignore permission but that player won't receive the messages the staff member sends in public chat.

**Comment by lackoSK** [comment]
Hello,

So if staff messages player who ignored the staff member the message will be sent? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Teriuihi** [comment]
Yeah that part is working fine

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org
