### ISSUE TITLE
DeathMessage improvements

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#165]
Hey,

When a blaze kills me with fireballs, the ''Projectile'' message gets triggered.

Even when I do it like this, the ''Projectile'' message still triggers.

>       BlazeBall: 
>         Killer: SMALL_FIREBALL
>         
>         Message: 
>           - '&3{player} &7heeft de vuurbal salvo van een &c{killer} &7niet kunnen ontwijken'
>           - '&3{player} &7heeft een vuurbal van een &c{killer} &7opgegeten'

This is the same for the Ghast, Stray, Skeleton, Shulker (every mob that shoots basically)

---

Could you perhaps tell me what needs to be under Projectile and what needs to be under Entity Explosion?

---

My previous deathmessage plugin had deathmessages for falling from ladders or vines, can you add these to the natural category perhaps?

---

I also noticed elytra doesn't have deathmessages?

---
When I fall from a high height, it says ''has died of fall'' but I can't find that string in messages.yml

**Comment by kangarko** [comment]
Hey,

You can use all damage causes as per https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html, but with ChatControl's formatting (Uppercased_First_Letter).

When blaze or other entity kills you with something, it is handled as a projectile event. Perhaps you can assert a rule inside Projectile death cause in messages.yml and set BLAZE as a killer there? (Haven't tested)

I am sorry that plugin probably had some custom measurements for falling from ladders or vines, I can't see that method easily in bukkit, but I take that as a future suggestion.

The death from fall is located at:
      Fall:
        Message: 'has died of fall'

**Comment by Sikatsu** [comment]
> When blaze or other entity kills you with something, it is handled as a projectile event. Perhaps you can assert a rule inside Projectile death cause in messages.yml and set BLAZE as a killer there? (Haven't tested)

This worked for a BLAZE, but when I did this for a GHAST this gave the default projectile message.

> I am sorry that plugin probably had some custom measurements for falling from ladders or vines, I can't see that method easily in bukkit, but I take that as a future suggestion.

Most likely, can be for later

> The death from fall is located at:

Fall is actually configured: http://prntscr.com/ef3fw1
Yet it still gave the ''has died of fall'' message.

I'm confused on how to get ghasts, shulkers, skeletons to work within the deathmessages. It makes it quite hard when not all deathmessages are by default within the messages file.

**Comment by c0wg0d** [comment]
I have been trying to figure this out as well and have not had any luck.  There doesn't seem to be any way to do it with how ChatControl currently works.

You would think that Killer: GHAST would work, but there is actually no way a ghast itself could kill you, only its fireball.  Same for blazes and skeletons.  It would be nice if there was an "origin" type setting so that you could have a "projectile" section which could be filtered by the type of projectile and who it originated from.  This would allow you to have different messages for players that died from arrows from a skeleton, arrows from a player (which should also have the Killer_Item feature to show a player's custom bow name), snowballs from a player, eggs from a player, etc.

There is also no way to customize witch death messages.  Players are always killed by 'magic' which could be potions from a witch or from a player.

Here is my entire Death_Messages section so far with comments on what I've tried and what works and doesn't work: https://gist.github.com/c0wg0d/c11d2237cd163d3e9f725f08b043d657

**Comment by Sikatsu** [comment]
Currently the deathmessages from ChatControl are not use-able, however I hope in the future it will be improved. I'm also hoping that every deathmessage is by default included in the config, without the need to add it ourselves. Thanks!

**Comment by kangarko** [comment]
@Sikatsu 

The behaviour as you mentioned does not work for ghast. I am working on a fix. However, I was able to get the fall message working. May I see your entire messages.yml file?

@c0wg0d,
The plugin has internal measurements and it detects the shooter of the projectile, that is considered the killer. 

I will look up the potion/witch difference.

**Comment by kangarko** [comment]
@Sikatsu 

Thank you for amazing configuration with explanations! I have look through it all and, because you provided such extensive and detailed information, I was able to fix the following:

- Primed TNT and Creeper Explosion has been fixed.
- Projectile messages fixed: Namely for Skeleton, Wither Skeleton, Ghast
- Magic messages are now different for potions from witches and players.

The reason why snowball or even snowman are there, is that those are valid entity types. The death messages uses the entity types to determine the type of the killer. No, I also don't believe that the player can die from a snowman or snowball. Not every entity type can be caught be the death message, this is normal Bukkit's behaviour.

Btw, you can't die from 'sweep attack'. This type is used in other events but not here.

I could not replicate the elder guardian giving the thorns death cause, it may as well been fixed with the changes above now.


Here is my messages.yml. I included your death messages, and removed a few that was duplicated or as you mentioned, can't be triggered.

http://pastebin.com/QWAGsHFz

Your death messages are so good that I would love to include then within the default configuration. Do I have your permission?

**Comment by c0wg0d** [comment]
That's wonderful news!  Thank you so much for working on all this!

Yes, I would be honored if you added my config to the default. :)  I have many, many more funny death messages to add so I can send you those too after I get them all configured, if you would like.

**Comment by kangarko** [comment]
Sure, if you can add more messages I'll be glad :) Just make sure you add them on top of the default configuration as per 7.2.6.  I have included you to credits, let me know if you don't wish your name in messages.yml

**Comment by kangarko** [comment]
I am closing this. If there are any more inconsistencies or questions, please open a new ticket so it's easier to follow through.
