### ISSUE TITLE
ChatControl hide Essentials join message.

### ISSUE THREAD

**Issue by CyreX12** [kangarko/ChatControl-Pro#1655]
Issue? :(
When I removed the plugin, The essentials send a message
(sry english)

**Comment by lackoSK** [comment]
Hello,

I am not sure what are you talking about. Please explain it.  

Sincerely,
Ladislav from MineAcademy.org

**Comment by CyreX12** [comment]
So, when someone connects, it doesn't show the message what I specified in the config.yml file, in essentialsx

**Comment by lackoSK** [comment]
Hello,

You need to disable them in ChatControl-Pro if you want to use Essentials join messages
![image](https://user-images.githubusercontent.com/53174757/81606974-39c84f00-93d4-11ea-8b4a-fbd4d0e6e6d1.png)

This is located in messages.yml

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org
