### ISSUE TITLE
fake leave/join/kick messages are broken

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1663]
@kangarko Hi!

Fake leave/join/kick messages are broken if i specify a fake username who isn't online.

Watch this picture. "józsi" is a random word with /chc fake leave józsi

https://imgur.com/q9YTOcM

Can it be fixed?

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
I am using the lastest version - 8.6.6
Will fixed in 8.6.7 then? :)

**Comment by lackoSK** [comment]
8.7.0 :)

**Comment by rErEaT** [comment]
okay, thanks a lot! i am waiting for that :)
