### ISSUE TITLE
ChatControl not working since 7.2.0

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#170]
Hey, I tried updating to 7.2.1 today (from 7.1.7) but my chat is no longer working.

I am using the interactive chat, with hover/click events, but somehow the whole chat just breaks and it shows [world2]<Sikatsu> instead.

When I rollback to 7.1.7, it's still not working, until I upload my old copy of configs on 7.1.7, then it works again.

**Comment by kangarko** [comment]
Hey,

apologies for the delay. I also saw your message at spigot forums, but decided to address it here. I don't know where the issue is coming from, unless I see some stack trace or configuration files. The interactive chat is working and stable as per default settings because it has been tested. 

1 Please provide me chat.yml and settings.yml file from the version where it's not working. 
2 Make sure there are no errors in the console. Also check the startup log.

**Comment by Sikatsu** [comment]
Hey @kangarko 

I'm still using 7.1.7, as the interactive chat is not working once I update. Even with default configuration, it isn't working.

> 1 Please provide me chat.yml and settings.yml file from the version where it's not working.

Chat.yml: http://pastebin.com/RXHsdbL5
Settings.yml: http://pastebin.com/Z4UqBxLg

> 2 Make sure there are no errors in the console. Also check the startup log.

I don't seem to see any errors, as it doesn't work even with default configuration.

**Comment by kangarko** [comment]
Hey,

I updated the configuration by running it on 7.2.3 and after setting Chat.Formatter.Enabled to true, the formatter was working. This option is also disabled by default in the default configuration.

**Comment by Sikatsu** [comment]
./chc reload is not working atleast for this option. Thanks!
