### ISSUE TITLE
1.16.1: Custom Javascript variables not functioning.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1779]
ChatControl Pro 8.6.8
Instead of displaying the returned value, prints {customjsname} into chat instead.

Example:
in formatting.yml:
- '&7Ping&8: {ping}'
will actually print Ping: {ping} instead of Ping: [VALUE]
where [VALUE] is returned by the function in javascript.txt:
```
define {ping}
script:
  player.getHandle().ping;
```

**Comment by JavaFactoryDev** [comment]
Hi,
thank you for reporting this here!

Regards,
- Leonhard

**Comment by kangarko** [comment]
Thanks,

The problem was that, when we downgraded from ChatControl 9.x to 8.x the variables were already changed at the library level, and the developers did not check this functionality. I take responsibility since it's my plugin and I just went ahead and fixed it.

New release will be available within 24h or less.

Matej
