### ISSUE TITLE
1.12.2 | Issue with AirBar and ChatControlPro

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl-Pro#1783]
Hi!

I bought [AirBar](https://www.spigotmc.org/resources/airbar.16649/) and installed it on my server. But, since, I have this message shown in the console everytime a player send a message:
**[ChatControl 8.6.6] AsyncPlayerChatEvent at HIGH(ignore cancelled = true) took 129 ms**

The issue was fixed in v9.0.4, so I still use it for now, but even with latest version (chc 8.6.8), the issue is still there. I tried with Java8, and now i'm using Java11, it doesn't change anything.

The problem is that this is a real spam in the console, and it seems to be the source of latency in the chat.
When players send their messages, there's like 1/2s latency before they're shown in the chat, and that's annoying.

Here's the config folder.
Have a nice day,
Thanks.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5013090/ChatControl.zip)

**Comment by relavis** [comment]
Hey,

Having this same issue on Paper 1.15 - no Airbar.

**Comment by ElBananaa** [comment]
Hey! This is a quick update:

I tried with CHC v8.7.1, the issue is still here, but the message is different:

[Server] INFO [ChatControl 8.7.1] cZ listening to AsyncPlayerChatEvent at HIGH priority took 125.47 ms
[Server] INFO [Admin] ElBananaa » ssdsd

The configs are the same as provided above, I didn't change anything.

**Comment by kangarko** [comment]
Hi there, the truth is, we spent a lot of time getting it to work properly on V9 but that version has been scrapped due to other problems. It cannot be fixed on V8 because the code is largely different. 

I am personally rewriting it back now, please migrate down to V8 as soon as possible because it will get security patches from me, just set Log_Lag_Over_Milis to 500 in settings.yml and we will then push the V9 when it is ready so you can use it.
