### ISSUE TITLE
1.16.1:Broadcast Initial Delay?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#1812]
Is there any way to have the broadcasting system to have a delay after you use the /chc reload command at all?

If not I would like to suggest this being added. :)

Thanks.
~Blood

**Comment by AngellitoX** [comment]
Hello!

As a friendly disclaimer, doing any type of reload is not recommended at all because it tends to break many hooks on the way, so anytime you modify something, it's always better to restart the server.

As for now, I don't think this can be implementet anytime soon but it could possibly be scheduled for the v9 series.

Angel from MineAcademy.org

**Comment by BloodshotPico** [comment]
Yeah I get that it can break something and it's always better to restart, however most people don't. At least I don't use the /reload command. :') /chc reload is better since it would break CHC stuff mainly if it was to error.

I would like to suggest it for v9 since the fallback to v8 is taking up a lot of time, so I don't mind. :)

~Blood

**Comment by kangarko** [comment]
Thanks for your suggestion!
