### ISSUE TITLE
1.16.1: Color GUI breaks other commands

### ISSUE THREAD

**Issue by ZeeRaider** [kangarko/ChatControl-Pro#1816]
1) Put your Minecraft version in the title.
1.16.1: 

2)  I use CommandPanels for my server, I'm finding that when I type any command for a panel to execute - it doesn't recognise what I'm typing. When I go into the panel YML, the chat has included the chat coloraturas codes from if I were typing within the general chat.
This is causing other commands simply not to work
There should be (maybe there is) a way to disable chat formatting entirely for command entry.

---!>

**Comment by ZeeRaider** [comment]
For some reason my report won't display, I shall post here ->

<!---
To report a problem or a bug with this plugin, please follow the three steps below:

1) Put your Minecraft version in the title.
1.16.1: 

2)  I use CommandPanels for my server, I'm finding that when I type any command for a panel to execute - it doesn't recognise what I'm typing. When I go into the panel YML, the chat has included the chat coloraturas codes from if I were typing within the general chat.
This is causing other commands simply not to work
There should be (maybe there is) a way to disable chat formatting entirely for command entry.

**Comment by AngellitoX** [comment]
Hello ZeeRaider,

This issue is caused because you are having a Chatcolor enabled from the Color GUI. Please reset your chat settings and you should be fine.

The reason behind it is that the Color GUI puts you a color/format at the beginning of every chat message you send indgame and in the final output, the plugin makes the code "&color" to be invisible.

Not sure if there's any way to improve that. (I am not a Java developer)

Hope this helps you. Nice to see you around!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Yes, unfortunately, ChatControl does what it can best, that is adding colors before your message and the other plugin can then no longer recognize them.
