### ISSUE TITLE
Timings improvements to PlayerJoinEvent?

### ISSUE THREAD

**Issue by Volgeop** [kangarko/ChatControl-Pro#1821]
Hi, I noticed that playerjoin event has a little bit more impact to perfomance, and whole chatcontrol too on my server. Maybe you could make improvements to it? I already tried reduce amount of placeholders, but didn't help. And I also heard that Auto messages on 8.X.X version aren't so well optimised too.

If you won't implement it, then there will be tps drops and lags and people will stop using chat control, for ex. I used on 8.x before LiteAnnouncer, then I switched to 9.X.X where the automessages were better, but now I'm back on 8.7.X and it's not so good... not just auto messages, also player join event etc.... just look to timings.

Yes, improve your system please.

https://timings.aikar.co/?id=d7837105e1c4497c9679a83da6e153b5 (from early startup)

https://timings.aikar.co/?id=0d227acd2533465abf69f67455d8917b - longer

**Comment by AngellitoX** [comment]
Hello,

Your timings are not showing anything critical from ChatControl. As I told you before, other plugins can have a huge impact on how ChatControl handles stuff and if ChatControl takes an inusual time to develop its tasks, thats what you will see on your timings.

You need to troubleshoot your plugins, it's abnormal to have tps loss with only 7 players.

I am closing this for now as your issue is not precisely coming from ChatControl.

Angel from MineAcademy.org

**Comment by kangarko** [comment]
The 8.x.x had issues with poor performance, @AngellitoX just so you know. Nothing I can do because I already spent weeks rewriting it on 9.x.x, please wait until that new version is ready.
