### ISSUE TITLE
Suggestion: /reply support last recipient

### ISSUE THREAD

**Issue by SioWolf** [kangarko/ChatControl-Pro#183]
I'd like to be able to toggle whether /reply should respond to the last received message (like it is now) or the last person the player has messaged OR received a message from.

The current set up is tripping many people up as we are accustomed to Essential's way of doing things.

**Comment by kangarko** [comment]
Asserted as an improvement.

**Comment by DanielVasquez4155** [comment]
Another thing about this. Doing /r is glitchy at times. Some people do /r and it goes to me instead of the person they intended to reply, I'm not sure why this would even happen. I have not messaged these people and it confuses them, and I will find a way to reproduce it myself. There should be a config option to choose either one of the /r functions, but our network also prefers the essentials way.

**Comment by kangarko** [comment]
Do you have bungeecords enabled @DanielVasquez4155 ? The messaging system works slightly different so I need to know what part shall I focus on.

**Comment by DanielVasquez4155** [comment]
Yes, we're using bungeecord.

**Comment by kangarko** [comment]
asdasd

**Comment by kangarko** [comment]
sds

**Comment by kangarko** [comment]
sd

**Comment by kangarko** [comment]
sd

**Comment by kangarko** [comment]
sd

**Comment by kangarko** [comment]
Hey, I've got a few more bug reports for this. I am closing this issue and creating a separate one just for this bug. As for the improvement, it has been added to the road map. I can't see when I will fix it, because right now I am busy with exams, but as soon as I have time this is the top priority.
