### ISSUE TITLE
1.16.1: Can't unload/load with Plugman since v8.7.x

### ISSUE THREAD

**Issue by TNTUP** [kangarko/ChatControl-Pro#1835]
Currently, it's not possible to unload then load with Plugman with v8.7.4.

I'm expecting to be able to unload then load without issues. Instead, it throws lots of errors, chat broken.

This attempt is easily reproducable, don't need either to give the stacktraces of it or the entire zip too. I can't simply restart the server for simple fixes as I really hate disturbing active players which this plugin is critical for chat between servers

PS: Seems to be worse than v9. Miss the stability with v8.6.6

**Comment by AngellitoX** [comment]
Hello, reloading the server has **ALWAYS** been extremely discouraged as it's known to break things since their very first development version.

As for now, I don't really think Matej will focus on making "reload" somehow stable. Please refer to this section for more information:

https://github.com/kangarko/ChatControl-Pro/wiki/Getting-Help-the-Right-Way#what-you-should-never-do

Closing this for now. Greetings!

**Comment by TNTUP** [comment]
> Hello, reloading the server has **ALWAYS** been extremely discouraged as it's known to break things since their very first development version.
> 
> As for now, I don't really think Matej will focus on making "reload" somehow stable. Please refer to this section for more information:
> 
> https://github.com/kangarko/ChatControl-Pro/wiki/Getting-Help-the-Right-Way#what-you-should-never-do
> 
> Closing this for now. Greetings!

Was always working with plugman unload/load, dropping a dislike on the plugin page

**Comment by AngellitoX** [comment]
I'm sorry this might not be accurate for you, but as I said, reloading support was extremely not recommended and the link I just provided to you was written by kangarko himself back in the 2017, so the information has been there for more than 3 years. 

The fact that reload was working in prior versions is not something we were supporting, and the fact that now is deprecated, shouldn't come as a surprise nor as a bug, because again, we have explicitly discouraged that for years. Apart from that, methods, events and code improvements have taken place which makes reload even harder to achieve due to how much ChatControl takes care of. On top of that, there are tons of plugins, including Spigot itself which recommends to never use /reload nor a reload plugin like PlugMan because it's perfectly well-known to break a lot of things.

Even though we appreciate your opinion, your concerns and your time, it's really sad to see you're basing your review upon a feature that we never stated in none of our sites and above all, never recommended, but thank you.

Best regards,
Angel

**Comment by kangarko** [comment]
@TNTUP I am willing to put up some effort in case we accidentally broke something and you claim it was working previously

Just tested on 1.16.1, seems to work fine:

![a](https://i.imgur.com/V8bZwMA.png)

So what exactly is broken for you please?

**Comment by TNTUP** [comment]
> @TNTUP I am willing to put up some effort in case we accidentally broke something and you claim it was working previously
> 
> Just tested on 1.16.1, seems to work fine:
> 
> ![a](https://camo.githubusercontent.com/c8fa7eb3a6d92d73fc579af54dcc974082b46c0b/68747470733a2f2f692e696d6775722e636f6d2f5638625a774d412e706e67)
> 
> So what exactly is broken for you please?

Placeholders are broken (probably caused by a recent PlaceholderAPI which causes this?), and spills out stacktraces https://pastebin.com/a9XqP7Dt

Before with Placeholder v2.10.6 and Chatcontrol 8.7.2 I was able to do that without problems but since I updated both plugins I'm forced to restart the server which sometimes in a rush hour I cannot and when its time to update when there's no people I was sleeping so I'm quite the impatient guy to wait everyone to disconnect as I hate disturbing them :(

I guess this might be caused with PlaceholderAPI as stacktraces point it out

**Comment by kangarko** [comment]
I understand, we have an open issue about PAPI, will try to fix this:

https://github.com/kangarko/ChatControl-Pro/issues/1799

**Comment by TNTUP** [comment]
Huh, I don't use any of javascript placeholders so I don't guess that could be caused by this?

**Comment by kangarko** [comment]
Good news, I dig inside PlaceholderAPI for you and I actually found a fix. A new release will be available tonight!

**Comment by kangarko** [comment]
@TNTUP if this issue was solved for you I appreciate if you consider rewriting/removing review: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/reviews#review-349956-13924 I put a lot of human hours into these plugins and it is in my best interest they work properly, unfortunately we have 10,000s of combinations of how plugins interact and catching all cases is hard and time consuming

**Comment by TNTUP** [comment]
> @TNTUP if this issue was solved for you I appreciate if you consider rewriting/removing review: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/reviews#review-349956-13924 I put a lot of human hours into these plugins and it is in my best interest they work properly, unfortunately we have 10,000s of combinations of how plugins interact and catching all cases is hard and time consuming

Yeah, hold on... done!

**Comment by kangarko** [comment]
Thanks!
