### ISSUE TITLE
worldedit command are threated as spam

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#184]
When using latest release of chatcontrol all commands are counted as spam:
example typing //brush sphere 95:15,95:10
it will be reported as advertisement

advertisement:
  Bypass_With_Permission: chatcontrol.bypass.ad
  Ignored_In_Commands:
  - //
  - /auction
  - /auc
  - /msg
  - /tell
  - /t
  - /w
  - /reply
  - /r

Instead using   - / it fix the issue

**Comment by kangarko** [comment]
Confirmed. I will fix this soon.

**Comment by kangarko** [comment]
Hey, I just did some testing. Some commands, like //set, are effectively ignored. Others, however, like //brush, since they can also be used without the double bracket like /brush, are not. This is out of ChatControl's reach because this is managed by WorldEdit.

You can either:

1) Ignore all commands by changing // to / in the whitelist (risky)
2) Add the affected commands manually, for example: 

Ignored_In_Commands:
  - /brush
  [...]

**Comment by xion87** [comment]
Thank you, i just whitelist brush and br as command (seem to be the only worldedit command blocked)
