### ISSUE TITLE
1.16.1: Join error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1848]
Are the recent updates not being tested? 8.6.7 had issues, and 8.6.8 has a new one..

Error on player join: https://pastebin.com/2i2PJ0dC

**Comment by kangarko** [comment]
The error you've posted is from 8.7.6, please use 8.7.8.

Yes I test every release on a multiplayer server with 2 accounts and BungeeCord. However, due to the amount of complexity and unique combinations the plugin offers, it may happen things will slip through the cracks, just as with any large software.

**Comment by Sikatsu** [comment]
Sorry for that, I had a lot of pastebin's open with errors. I must've copied the wrong one. @kangarko 

This seems paper specific and happens on every player join: https://pastebin.com/Uzrvn3mU

**Comment by kangarko** [comment]
Yep, that error will get patched. I don't want to release two releases a day, it's just annoying to many users, so I will push it by the evening. Thanks!

**Comment by Sikatsu** [comment]
On the other hand, users can update once they have the time to do so, they don't have to update immediatly. But that's me personally, I think it's just good when bugs get patched as soon as possible ^^
