### ISSUE TITLE
1.16.1: Admin chat formatting

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1854]
Hey, I use an admin chat format like this: https://pastebin.com/FmsG1kRH

But as you can also see in the pastebin, it will show my messages twice if I sent something from the console.

Can I do anything to prevent that from happening?

**Comment by AngellitoX** [comment]
I had never seen this before and it looks a bit counterproductive. Console will always have OP/all permissions, therefore, by speaking from Console you're triggering both admin messages.

Personally (really, personally), I consider that highlighting the owner specifically in the AdminChat is unnecessary because, if they belong to your staff, they already know who the owner is, so yeah, you get my idea.

Anyways, there are different ways of approaching these I assume. For example, JavaScript would be one, complex but should work.

Another workaround is set your owner group a Suffix color (in case you're not using it) and include the placeholder `{suffixcolor}` to before the message, so your output looks colorized. It's important to mention I haven't tested this approach, I just googled a few stuff.

Hope one of them can work for you!

**Comment by Sikatsu** [comment]
I used to use /chc color, but since it doesn't support hexcodes yet I made a seperate formatting with a hexcode for my chat. But that didn't work within the adminchat, so I did it for the adminchat as well since I was used to it. But yeah, it indeed triggers both admin messages then..

I'll see if I can find my way around it then ^^

**Comment by AngellitoX** [comment]
Cool, if you ever find a workaround, let us know because it could be something nice for some people! 

I'm closing this for now. Thanks a lot!

**Comment by kangarko** [comment]
Got it, RGB for /chc color is planned & on track.

Given your user case I will add "No_Console" option for the format part in CHC 9.1.0
