### ISSUE TITLE
1.12.2: /Ignore seems to crash users with CHC 8.7.10

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#1867]
Paper 1.12.2, Using the latest 8.7.10 updated today, multiple issues with it.
This issue is crashing the server when people use `/ignore`

Here 4 crashes it caused this morning.

1) https://gist.github.com/TomLewis/031698dfd7e95f8e441c4df43ccb8453
2) https://gist.github.com/TomLewis/562f896e59fe7270068e3ccd943df8db
3) https://gist.github.com/TomLewis/5250437766a6040204ecebe27ec4c4cd
4) https://gist.github.com/TomLewis/4b68b7cccd43898affb7c0c7f6641614

**Comment by Sikatsu** [comment]
Isn't this more of a conflict with essentials?

**Comment by james090500** [comment]
I agree, can you make sure players dont have the essentials ignore permission and they're definitely using ChatControl

**Comment by FrozenBeard** [comment]
> 
> 
> I agree, can you make sure players dont have the essentials ignore permission and they're definitely using ChatControl

They do not have essentials ignore permission, and they are definitely using ChatControl ignore, as you can see from the 4 error logs I posted.

You both must be unaware that ChatControl actually talks with essentials to work with essentials as a soft dependency.

Also as I have already said, This issue did not exist until I updated chatcontrol pro, please use your brains! I havent changed essentials in 6+ months!

**Comment by james090500** [comment]
First of all, your negative attitude isn't appreciated for people trying to help you. 

Secondly from the error you posted, it looks like it is looking through the Essentials usermap and then trying to load each config files. Now either its trying to load to many files so Paper thinks the thread has died or it gets stuck trying to load an Essentials Config.

Check how many Essentials userdata files you have. Are there 10s of thousands? Secondly I would recommend updating Essentials if you haven't done so in 6+ months...

**Comment by FrozenBeard** [comment]
> 
> 
> First of all, your negative attitude isn't appreciated for people trying to help you.
> 
> Secondly from the error you posted, it looks like it is looking through the Essentials usermap and then trying to load each config files. Now either its trying to load to many files so Paper thinks the thread has died or it gets stuck trying to load an Essentials Config.
> 
> Check how many Essentials userdata files you have. Are there 10s of thousands? Secondly I would recommend updating Essentials if you haven't done so in 6+ months...

The reply I got wasn't appreciated being treated like a child. Don't act like an idiot if you don't want to be treated like one.
Ticket facts stated, that I should not have to waste time repeating.
1) This only happened when I updated ChatControl
2) It tells you in the crash logs its ChatControl
3) I do not have permissions for Ess Ignore, only ChatControl.

Its not Essentials but its the way ChatControl is using Essentials. 

I have 250,000+ unique users, so thats 250,000+ Ess files.

Which is still nothing to do with ChatControl Ignore, as is updating Ess, because they have compiled against 1.13+ and are dropping backwards comparability testing, which again I stated in the first ticket, which means I cannot update it without unknown bugs that could arise, if its not broke, don't fix it, which I attest to todays update to ChatControl!

**Comment by Sikatsu** [comment]
Being treated like a child? All I did is asking you a question. No need to ''thumbs down'' and behave like you currently do. Calling us idiots and telling us to use our brain, it makes zero sense. Good luck with your issue.

**Comment by AngellitoX** [comment]
Hello, whereas I appreciate you contacting us in order to help you out, I also discourage the way you treat people. They did nothing but try to help you in the way the found best, therefore there was no need for you to talk to them the way you did, especially when they didn't need to reply in the first place. Even though we may understand your frustration, we are all humans and I bet you we have all passed through the same frustration, but anyways we are always trying to as open as we can be in order to help others, so please, keep that in mind.

As for your issue, If you are updating one plugin, you should also update the rest and especially the ones dependant to it, in this case, EssentialsX. Outdated versions may work "fine", but they get upgraded and improved over the time and also fixing a few stuff on their way or even changing the methods they use to handle information/data, and if you are telling here that you haven't touched EssentialsX for more than 6 months, it means that you are basically and almost 500 builds behind, so there's definitely an issue coming out of your negligence, and there's no way we could give support to it.

As a sidenote, I was unable to read your issue because, just like in your other ticket, your logs have expired. I'd definitely recommend uploading them on pastebin.com or somewhere better.

**Comment by AleXTVC** [comment]
Extremely hilarious to read him say "open your brains" while being almost 500 builds behind lmfao, best timings ever.

**Comment by TomLewis** [comment]
Im very sorry, im just trying to get support for a premium plugin I paid for, and I got 2 replys from people that didn't read the initial ticket, the reply's I got were both from lack of them reading the information in the ticket.

Please do link me to the changelogs where you mentioned you broke backwards comparability to EssentiialsX, I know its very hard to read tone in messages, but when I said 6 months it was an estimate/guess to their release cycle and not using development builds.

Again, running a 1.12.2 server in an age of 1.16.2 you have to be carful on what you update.


If you have broken backwards compatability with Essentails, which is causing your premium plugin to fail and crash servers, you should at the very minimal either write this in your change logs or reply to your customers without being toxic and actually readx the ticket that include the information you are asking me to "fix".


You have confirmed that there is a bug with ChatControl and EssentailX, the reply I got was telling me it was an Essentials plugin issue and not ChatControl which makes my anger valid.

All information was in the ticket.
No information was given about breaking backwards compatibility.
None of you are the developer.

I am very disgusted with how you have all decided to treat me in replys to this ticket, I am a human being and your passive aggressive replys 

1. I have given full ticket information, which was blatenly ignored
2. passive aggressive hostile replys
3. There is a MAJOR bug with chatcontrol pro (PAID) is not being fixed because of your keyboard warrior egos, I pointed out that your replys were wrong and you are wrong that is all and you took offense.

I do not want a reply unless it is specifically about this bug I have posted, please STOP going off topic if you can not help fix the bug.

**Comment by AngellitoX** [comment]
Nobody went off topic until you started treating people the way they didn't deserve just because they extended their hands for another unknown person. Don't act like the victim when after they politely answered to you, you attacked them with comments such as "use your brains". My answer was a proper answer for that and was everything but "aggressive hostile", but whatever.

Straight back to your original question:

1. Again, your 4 links are expired and unreadable, please fix so I can even take a look to them to try to understand what's happening.
2. Dev builds (at least from EssentialsX) are known to be stable and there hasn't been any major problems at using them. Instead, they fix a lot of issues on their way, and if you through here https://ci.ender.zone/job/EssentialsX/changes you will see that from build #893 to 897 there were a lot of movements related to their ignore system which can be causing your issue.

Developers don't upload and update builds for nothing. EssentialsX is a full crew working day and night and staying outdated is like not appreciating all their efforts. 

And yes, we are indeed a premium plugin, but that doesn't mean you can talk to us the way you're, especially when we are actively responding to you, so I also think the drama is coming from both sides unnecesarily. 

For now, the issues (in general) will be fixed until the weekend, and for now all we can do is wait. In the meantime, if you feel like updating EssentialsX will set your server on fire, I'd recommend running some tests with the latest version of EssX and ChatControl in a testserver with your data included, and check if your issue persists.

Hope this information helps you, and if there's anything we can do for you, we'd be pleased to do so.

Angel from MineAcademy.org

**Comment by TomLewis** [comment]
@AngellitoX Please do not reply, this is not solving the ticket issue. 
You being an [Internet hero](https://www.urbandictionary.com/define.php?term=Internet%20Hero) is in itself toxic. 

Like I told you in another ticket, My username change was accepted yesterday, I have updated them as you are late to this ticket, it was posted yesterday when I had a different username. I have updated them for you.

Please tell me directly in one sentence without being a internet hero **Did you break backwards compatibility with EssentailsX**
**If so where is this in the changelogs?**

**Comment by kangarko** [comment]
Wow.

To clarify: Tickets are for tech issues not for personal issues. 

I understand you are frustrated because a recent change in offline players look up now happens on the main thread and takes the whole server down in your case. This is my mistake and not anyone else's on here because I called Essentials for that and did not check their code how they do it. I am going to fix this problem in a few hours.

Nevertheless, personal attacks, defamatory and otherwise useless posts as to argue with people and not the problem itself won't be tolerated.

**Comment by kangarko** [comment]
I wrapped the code in async block while resolving the names and then sync again when saving on disk and performing other operations. My testing indicated no problems what-so-ever however please be online while you install this on a larger server and let me know if anything comes up.

![a](https://i.imgur.com/Cewi2is.png)

**Comment by TomLewis** [comment]
Good luck!

**Comment by kangarko** [comment]
Just a headsup, I reached out to you yesterday regarding a delay in this release.

I had a lot of unexpected work since this turned out to be a deeper problem so I had to rewrite how we store data in data.db etc. Essentially now there will be a "Name" part in data.db for each active user to avoid looking up the UUID on the main thread.

![a](https://i.imgur.com/jNST3hH.png)

I got the plugin without compile errors but still requires more testing and fine tuning. Happy to hear you found the older release working and I will prepare the new one within 2-3 days, realistically.

**Comment by TomLewis** [comment]
Brilliant thanks for the update.

**Comment by TomLewis** [comment]
@kangarko Right, I run this on my test server with my data.yml and my ChatControl_Data MySQL Table, it took 1 hour 10 mins to complete. 
I have a question, in your changelogs it says that you do a mass import from Essentials first time running this update, so I assume I will need to run this on my live server to get all that data from Essentials files? Will this also pull any data from the worlds playerdata too? Im trying to see if I can do this on my test server, but I will need to know what files you are using to pull data from.

Im assuming I will need to have all Essentails data, and Im also assuming I will need the worlds playerdata folder if I were to run this on a test server as this would be 70 mins downtime to complete on production. 

 Also looking at the finished MySQL table, I see a lot of empty array data in Ignored_Players for every single ignore, for exmaple heres one players ignored list `{"sj_brotherhood":"","hot_gamergirlxxx":"","cyberking21":"","melonisnotafruit":""}` After each user its got an empty `""` is this for related information to the ignored user? Also what happens if that user they have ignored changes their username? Shouldn't you be ignoring based on UUID not username? They would change their username and would not be ignored again then.

**Comment by kangarko** [comment]
Hi Tom,

Sorry for the delay, had to leave my house for the this week, family reasons. I can code a new import command that will import Essential data on-demand so you don't have to worry about loading the plugin at the correct time.

Regarding the empty maps, this is a placeholder for future data. Yes, I attempted to convert all names into UUIDs however the current system was then blocking the server. In the future we'll mitigate this by using a converter table with uuid:last_known_username to pull from there to avoid making blocking requests to the internet.

**Comment by TomLewis** [comment]
> Hi Tom,
> 
> Sorry for the delay, had to leave my house for the this week, family reasons. I can code a new import command that will import Essential data on-demand so you don't have to worry about loading the plugin at the correct time.
> 
> Regarding the empty maps, this is a placeholder for future data. Yes, I attempted to convert all names into UUIDs however the current system was then blocking the server. In the future we'll mitigate this by using a converter table with uuid:last_known_username to pull from there to avoid making blocking requests to the internet.

Aha right! so we will require another convert later.
You shouldn't need to do an API request to mojang as UUID is saved in a few places already;
EssentialsX has: `plugins/Essentials/usermap.csv' which has data for every single user thats logged on saved like this `godsdead,93e8b4dc-672b-41c6-bb75-e68960d60184` I have 266896 lines in this file, and I have 267900 files in my essentials userdata folder, so its close enough to get a UUID match then the rest can be looked up via the API.

**Comment by kangarko** [comment]
Brilliant idea, I'll hook into that! This or the next week first priority.

**Comment by kangarko** [comment]
Correction: I will add the import command to CHC 8, then UUID migration or mitigation in CHC 9

**Comment by TomLewis** [comment]
@kangarko Updated to 8.8.4 today, it did its cleanup, then I ran the essentials import. 
I re-enabled `Ignore.Enabled` gave the permission back to users, got a user to run the `/ignore` command and it took down the server straight away.

https://gist.github.com/TomLewis/1ed62c9d67aa8868f733a973a196b9cd

**Comment by kangarko** [comment]
Hey, I apology, this did not show up testing on my online mode test server.

You are correct, while we longer pull ignore from Essentials, it still looks for Essentials nick to ensure you can ignore players by their nickname. Apparently the nick-lookup method from Essentials was blocking but didn't show up during the testing.

I've put the nick-lookup code in the async method, so now it's going to take around 0.5 seconds for the command to return however this will no longer block the server.

![a](https://i.imgur.com/DefmKII.png)

In CHC 9.1, we're going to have our own nicks system so this will permanently eliminate the problem. If it's still problematic on your setup I can add a setting option to disable nicknames completely.

**Comment by TomLewis** [comment]
@kangarko Did this update get pushed to 8.8.6?

When you do implement nicknames, my only suggestions would be to include a nickname list, so you can list every person that has a nickname, its the biggest flaw with Essentails nicknames, not being able to see an overview of everyone with nicknames.

**Comment by kangarko** [comment]
Thanks. Please vote here: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-3-25-sale-%E2%9A%A1.10258/update?update=361124

**Comment by kangarko** [comment]
Yeah CHC 9.1.0 will also have pagination system for messages so we could easily list 100s of nicknames 👍
