### ISSUE TITLE
Separate Chat on Hub + Hide Bungee Messages On a Server

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#189]
Hi there, here is my current setup: Bungee with 4 servers.  **I would like to separate one of the servers (hub) from the chat room.**

I currently have a channel called "global" and everyone has the _chatcontrol.channel.global.autojoin_ perm (as well as join/leave/send).  BungeeControlBridge has messages.enabled set to true. 

I would like to separate out the hub server from the rest of the network's chat channels.  I have tried the following ways:

1) Making a second channel and giving the _chatcontrol.channel.lobby.autojoin_ perm and negating the _chatcontrol.channel.global.autojoin_ perm on that server using luckperms.  But players who are already in global channel stay in global channel when they switch to the hub.  If I remove the global channel on one server but not the other, players are stuck in an unformatted vanilla chat (<playername>)  and get an Internal error when trying to use any of the ChatControlPro commands.  A look into the mysql database shows them as still being in the channel even though it doesn't exist on that server.

2) I tried setting Chat.channels.enabled false in settings.yml which seemed to work best--but people on the hub server would still get connect/disconnect/server switch messages from BungeeControlBridge.  I tried setting Hide_Join_Quit_Kick_Messages false in messages.yml and removing the server from config.yml of BungeeControlBridge but the quit/join/switch messages are still there.  And there is also the side effect of a multitude of errors in the logs because the server is receiving messages from bungee and not knowing what to do with them because chat channels are turned off (java.lang.NullPointerException: Channel not installed on this server: global).

Any suggestions for a configuration to have a global chat for 3 servers and a separate chat for 1 server? My method #2 seems to be the best bet so far--but I really would like for there to be some bungee-wide channels (e.g. admin chat).  Ideally I would like there to be an ability to have some global channels spanning some servers, but to be able to separate them on one server.

I am on ChatControlPro 7.2.4, latest Waterfall build for bungee, and paperspigot 1.10.2 build 916.

Config files:
settings.yml on hub server https://hastebin.com/qisutukepi.php
chat.yml on hub server https://hastebin.com/ogojujavec.php 
(the are other channels but the ones in question are global and lobby in this particular instance)
config.yml (BungeeControlBridge) on bungee server https://hastebin.com/oquyayerer.http
(the hub server is named "public" and I had removed it from the server list hoping that it would not receive quit/join/switch messages). 

Thanks for any help you can offer.

Mike

**Comment by braceyourself07** [comment]
I think I may have resolved this by changing MySQL.Enabled_In.Channel to false so that the last channel wasn't being stored in the mysql database.  It still remembers the last channel I was in, so it's hard to say if it still works or if it's just remembering my last channel.  If I change channels, go to another server in the bungee, and then return to the original server... I'm in the same channel and not reverted back to the one in the autojoin permission node as I would like to happen.

Assuming the above is a working solution, my next task is to try to eliminate the join/quit/switch messages from the hub server but still keep it on the other servers.

**Comment by braceyourself07** [comment]
I've also isolated one other issue that is helping.  I was "/op" on the individual servers which was causing all of the autojoin permissions to take effect.  Our permissions plugin is designed to run without using /op.  Once that was fixed, the autojoin perms now make sense and operate accordingly.  Now the rest of my situation is figuring out how to suppress the join/quit/switch messages on only 1 server out of the network.

**Comment by kangarko** [comment]
Hey braceyourself,

first of all thank you for taking your time to provide me such extensive feedback and guidelines to your problem. It greatly reduces the time required to research it on my own. I see that you are being a very responsive server owner and I have no doubts that your server is of a high quality.

The players stay in their channel because of two scenarios:
* a) The inbuilt cache within the plugin on your Bukkit server. This cache stores players' information, for example their last message for antispam, or their channel. The cache is cleared on server shutdown or reload.
* b) The MySQL database. As you already know, it is possible to turn certain data that are saved off in '**MySQL.Enabled_In**' in settings.yml. You can configure each server to have its unique database, but this is not recommended as the core idea of MySQL originally was to connect ChatControl's data over your bungee network (but still; it will work just fine). 

At present, there is no native option to "set" players to a specific channel when they login, aside from the _autojoin permissions_. On the other hand, there is no _autoleave permissions_ so as you correctly stated, players will already remain in their old channel.

You can use third party plugins to execute the "**/channel switch**" or "**/channel join**" commands when players log-in. They have their limitation because they only allow themselves to be executed when player is a) in certain channel already for switch command, or b) player is not already in said channel and c) player has all permissions and all conditions are valid.

Regarding the error, the missing channel exception will pop up when you/server attempt(s) to  send a message directed to a specific channel to another server on which the channel is not configured. There is nothing to do about it, it is there for security.

Lastly, I am preparing a "/channel set" command that will forcefully assign a channel to the player, regardless of which channel they are in, or which permissions they have. I thought you may take benefit of it and use it in some other plugin to launch it on players' join. I do my best to finish it today (but no promises :P).

**Comment by kangarko** [comment]
Regarding the join/quit/switch messages, there are managed in two ways

* a) From ChatControl's messages.yml. This file and messages therein are effective within your one Bukkit server only. Those are aimed to cover the Mojang's join and quit messages. You may disable or customize them individually for each server.

* b) From BungeeControlBridge's settings. Those are extra messages not covered by Bukkit or Bungee. At present, the messages are effective and visible for all servers on your Bungee network. Would you like an option to hide them on individual servers?

**Comment by braceyourself07** [comment]
Thank you so much for the kind words!  I know your time is valuable in helping others with your fantastic plugins and I know any information I can provide can save you a little bit more time.  Plus I think the act of thoroughly typing it out helps me outline what I've done to troubleshoot and gives me more ideas to try even after I submit the question/issue.

I feel a bit derpy though because most of my issue was solved when I realized I was OP'd on the server and it was making me autojoin the multiple channels I had set up, making me think something was misconfigured.  When I removed myself from OP (which I normally do anyway, and only use permissions for staff privileges) in combination with removing saved channels from MySQL, everything works as I would like it to!  

The remaining issue was that players on the hub were seeing the join/quit/switch messages from the other servers.  **So, yes I would love to see an option in BungeeControlBridge to turn off receiving join/quit/switch messages per server.** This way players in the hub would be able to see others in the hub join/quit, but not when they are moving about the rest of the network.

Certainly the upcoming /channel set command will be very useful!  As I like to employ break-out channels for when the network traffic is higher and people can go into individual "rooms" (other channels) for quiet conversation away from the global chat.  Not hugely important on my network, since with autojoin it's almost guaranteed that a player is going to be in SOME kind of chat channel already upon joining the network.  But for those that happened to leave manually, a player gets stuck because they don't know how to /ch join (and my aliased commands are set to /ch switch) but a staff member is usually able to help them along without issue.

Again thanks so much!

Mike

**Comment by braceyourself07** [comment]
Just to follow up, my dev is making a multi-server world system so my servers will eventually be purely for load balancing and all feel like one server "area".  Rather than trying to set up a "bungee of bungee networks" to isolate areas, the added features to BungeeControlBridge to turn off messages per server would be fantastic.  Just to clarify this is ideally what I would like to do:

New player connects to the server for the first time--connects to the hub server.  Hub server does not display join/quit messages (either local join/quit or remote join/quit/switch) as it's simply a passthrough.  

Player has 2 "areas" they can go to... member area or community area.  The member area is a group of 3 servers.  And the community area is only 1 server currently but plans for increasing this depending on growth).  When the player connects to these areas, I would like these groups of servers to display join/quit/switch messages within themselves.

Hub --> Server Group A (Server1,2,3)
        --> Server Group B (Server 4,5,6)

Server Group A would see join/quit/switch messages among themselves and likewise for Group B, but they cannot see the join/quit/switch messages for each other.

Not sure if this would be possible with BungeeControlBridge, but even with the option of just being able to turn off messages (or perhaps specific messages like just turn off switch messages but leave join/quit messages) would be great.

**Comment by braceyourself07** [comment]
Or actually how about this... just be able to disable the switching messages globally.

**Comment by kangarko** [comment]
Hey, I just pushed a new update to [BungeeControlBridge](https://www.spigotmc.org/resources/bungeecontrolbridge.13079/), and you may now hide individual messages completely by setting them to '' or 'none' in config.yml in that plugin :)

**Comment by braceyourself07** [comment]
Oh that's incredibly awesome of you, thank you!

**Comment by kangarko** [comment]
Np, if you enjoyed the plugin, maybe you can give it a review if you already hadn't :)
