### ISSUE TITLE
Add compatibility for KingdomsX

### ISSUE THREAD

**Issue by KyroOW** [kangarko/ChatControl-Pro#1904]
Please add support for KingdomsX chat prefix https://www.spigotmc.org/resources/kingdomsx.77670/ with the relation color placeholder which looks like that in the config:

"&8[%kingdoms_rank_color%%kingdoms_rank_symbol%&8]&7|&8[%kingdoms_relation_color%%kingdoms_name%&8] %displayname% &7» &r%message%"

Right now there is no way to properly show the prefix of Kingdoms (via placeholders yes but too much things are missing) only way right now is to use Kingdoms chat formatter, which makes me loose all chatcontrol features.

It can parse the prefix as the placeholder {kingdoms} but it doesn't work in chatcontrol.

**Comment by AngellitoX** [comment]
Hello, have you tried using { } brackets instead of the % % symbols for all of your placeholders? It should work without problem.

Let me know if that solves your problem.

I'm marking this as solved for now. If your problem persists I'll reopen it with no problem. Thank you!
Angel from MineAcademy.org

**Comment by KyroOW** [comment]
Hello,

I did mean the {kingdoms} placeholder, but it doesn't work

**Comment by kangarko** [comment]
You can try using PlaceholderAPI for this
