### ISSUE TITLE
Mention bug with chat color

### ISSUE THREAD

**Issue by LoSCraft-Network** [kangarko/ChatControl-Pro#1906]
<!---
**IMPORTANT:** Do NOT post error logs here, use pastebin.com to upload them and post us a link!

To report a problem or a bug with this plugin, please follow the three steps below:

1) Put your Minecraft version in the title.
1.15.2

2) Be clear: What is your current situation, the desired situation, and your problem?
Example: I want my chat to be formatted in vanilla but not the creative world. My current situation is it is being formatted everywhere. I made sure not to use reload and haven't found any console errors. What I am doing wrong?
When Mentioning a player, chat will ignore chat color and it will come out white.

https://i.imgur.com/tpzRUZH.png

**Comment by LoSCraft-Network** [comment]
Version:
1.15.2

When Mentioning a player, chat will ignore chat color and it will come out white.

https://i.imgur.com/tpzRUZH.png

**Comment by LogGits** [comment]
/me coughs #1453 
@kangarko This is still a thing on paper 1.16.2 build 174. It's good to know I'm not the only one having this issue xD

**Comment by Danielpeter-99** [comment]
Up, also happening to me.

**Comment by kangarko** [comment]
Long-term issue on CHC 8, won't be fixed until CHC 9 is out, that will be next month, thanks!

**Comment by LogGits** [comment]
@kangarko it was never tested on version 9. The non-kangarko dev was the one who said it was fixed in v9. Just to give you some context from what i have observed.

If a player has a gui colour enabled, this mention bug doesn't happen. This (from what i have noticed) is because that persistent gui colour adds the chatcolour to the beginning of the string. Without a chatcolour explicitly mentioned (by the player) at the beginning of the message sent, the text after a Mention will turn white.

**Comment by kangarko** [comment]
Thanks for explanation, when I am rewriting the formater I ensure that, sound notify restores the proper color regardless what part of the chat it is coming from.
