### ISSUE TITLE
item.yml not working

### ISSUE THREAD

**Issue by SniffieFTW** [kangarko/ChatControl-Pro#1965]
so i have been trying to do the item.yml for about 30min now and I just can't seem to get it to show the hover text. I am using the example that is given and it won't show the hover. I have tried typing item, [item], {item}, "item" and none of them work.

I have essentialsX essentials chat, luckperms, and vault all installed to make sure it would work and it still won't. Can someone please help me out?

**Comment by AngellitoX** [comment]
Hello, your issue is most likely because you have Essentials Chat. This plugin is not meant to work alongside with ChatControl Pro as both do work for the same purpose. 

Please, try uninstalling EssX Chat and keep ChatControl only and runt tests again. Hopefully it might work for you.

Closing this in good faith it will be solved. Comment below if you need more help.
Angel from MineAcademy.org

**Comment by kangarko** [comment]
The [item] placeholder yet does not work. It will come later in CHC 9.1.0
