### ISSUE TITLE
Paper 1.15.2 Block message

### ISSUE THREAD

**Issue by cantercrow** [kangarko/ChatControl-Pro#1977]
Hi,

I would like to block or change the message below sent from WorldGuard, how would I do this?

Hey! Sorry, but you can't PVP here.

Regards

**Comment by kangarko** [comment]
Unfortunately since MC 1.7, every message is a chat component. What we see internally is this:

hey:
- color: DARK_RED

sorry, but you cant pvb here:
- color: RED

So maybe you can only match the other part of the message, however due to this nature packet rules matching cannot be guaranteed on messages with multiple colors/formatting.
