### ISSUE TITLE
How to customize player death messages sent to DiscordSRV?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1988]
- Hi, I am trying to customize the way Death messages are shown in DIscordSRV channels, at the moment they look pretty bad, it simply says `{player-prefix} {player-name} {player-name} {death-message}`

- All the placeholders work and look fine, however I would like to remove the duplicated user name and prefix from death messages.

- How can I do this? I could not find the option in the formatting file or any other file. 
Thanks in advanced!

**Comment by kangarko** [comment]
Thanks, I will have a look when I have time 👍

**Comment by kangarko** [comment]
@LeehamElectronics implemented as rules:

![a](https://i.imgur.com/6r8Enyf.png)

In this preliminary example, you'll simply catch a death cause and then send it manually to your chosen discord channel in your chosen format. Gives you the most flexibility and all customization options since all variables are supported.

**Comment by Rawxdealz** [comment]
Is there a way to push the costum death message to discord? Ingame i have the costum message but it sends the minecraft default to discordsrv.

**Comment by LeehamElectronics** [comment]
> Not on ChatControl Pro, I am sorry. On ChatControl Red it is be possible through our rules system.

Wow 1 year ago! Time goes fast, thanks Matej for the clarification.
