### ISSUE TITLE
1.16.3 - My config version changed (messing up my settings)

### ISSUE THREAD

**Issue by EnderGamingFilms** [kangarko/ChatControl-Pro#2000]
So I had config version 25 where the format settings were all in separate files that looked like https://pastebin.com/qTyL7uaG ... After I updated like a few days ago it appears that it has gone back to the old way of formatting. I had just changed everything over to work and now none of my settings are working and I do not have my previous config stored. Is it worth translating them back to the "normal" format?

**Comment by AngellitoX** [comment]
Hello there, it looks like you were using the well-known failure version of ChatControl v9.0 which was deprecated a few months ago. Unfortunately we stopped giving support to that version since then as it contained a lot of bugs unable to solve.

The format from latest 8.8.X versions are the original ones and therefore, the ones we give support to. The actual version config is "24".

I deeply apologize for the inconvenienve and I hope you can understand us! Thank you for the time!
Angel Avila

**Comment by EnderGamingFilms** [comment]
I guess to be more specific, what I wanted to know was if you will be going to the new format or staying with the old for future updates?

**Comment by AngellitoX** [comment]
Oh! I apologize for the confusion.

As for the CCP 8.8.x series the format will remain the same, and once the new 9.1.0 versions are release, I'm pretty sure there will be a similar format and an easier way to do the transition between both versions. :) 

In short terms, the format from the failed v9.0 versions will no longer be used.

Sorry for the confusion!

**Comment by EnderGamingFilms** [comment]
Alright, thanks!!

**Comment by kangarko** [comment]
DO NOT USE THE V9 BETA

It is broken and was removed since. You'll get no support. This has been stated many times over. Just regenerate all configs under 8.x.x.

PS: Congratulations for making the 2000th issue. Send a PM to me on SpigotMC and you'll get one premium plugin for free ;)

Thanks
