### ISSUE TITLE
1.16.3: Only errors on chat now.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#2044]
Works for a short while and then these errors happen every time anyone attempts to chat anything:
https://pastebin.com/2n1GPTE5
(from errors.log)
https://pastebin.com/PZQGc5aZ
(from latest.log)

ChatControl Pro 8.8.17 (will be reverting for the time being).

**Comment by MithrandirCraft** [comment]
Same: https://gist.github.com/MithrandirCraft/d164a756f83afa2effab25b80083bb60
Basically no one can say anything.

Please stabilize this plugin, it's every single update you guys do that breaks everything. Please point to a stable build and don't publish until the next build is decent.

**Comment by mrcoffee1026** [comment]
Feel it's pretty rare we get an update that fails in this way.  Also, when I first ran it, it appeared to function as expected.  This may be one of those issues that only occurs with multiple people on the server, hopefully that helps you track it down.

**Comment by eyebrawl123** [comment]
the same mistake with me

**Comment by kangarko** [comment]
Thanks, I'll fix that asap.

Sorry guys for this. We've changed things in our library and no longer allow for checking null permissions. I've of course tested ChatControl Pro to use the new system but due to fact there are 229 cases where this is called, 1 case got slipped under the roof: https://i.imgur.com/79RTjgj.png

There may be more instances where this is called and will complain so all I ask is to use the next version and report anything coming up. Yes I'll do my best to patch hundreds of cases by hand but still.

**Comment by kangarko** [comment]
Okay I made it not crash but print a fake error and warning message instead. Please post them below in case it happens again.
