### ISSUE TITLE
Put all default config files in the wiki

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#2068]
I looked around and I could only find the default settings.yml in the wiki.
Please add all of the default config files to the wiki.

I am editing sections in my messages.yml and there is a lot of clutter that I'd like to remove. It is in the way and so it's best to remove it, but it would help to have easy access to see it again in the future.

**Comment by AngellitoX** [comment]
Hello there!

Thank you so much for the idea. For future reference, you can review the `yml` documents by opening the `ChatControl.jar` using WinRAR. That way you can check the default files anytime.

This is also a better idea because if there are any changes/additions/deletions on the files you can easily check them and compare with your custom files as soon as the update is released in SpigotMC.

Hopefully this information can be helpful, and once again, thank you for reaching us!

**Comment by kangarko** [comment]
ChatControl 9 will have settings.yml with comments on always. Thanks for suggesting this, but you can always just extract those from jar as Angel has suggested.
