### ISSUE TITLE
1.8.9: Join event performance

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl-Pro#2077]
Hello,

The join event is insanely heavy. Sometimes taking about 350ms, with a server with 250+ players, that's make big lags...

I know there was an issue with the join event who was sometimes corrupting something, but it really need to be investigated. It wasn't happening before ChatControl 8.6.5 ...

Best regards,

**Comment by kangarko** [comment]
Hi and thank you for reporting.

The issue comes down to connecting to MySQL database on the main thread. We had to make this change for safety and I would not stay on such an old version due to other concerns the old system had.

ChatControl 9 will completely offload these events so that even a heavy load with slow database won't be noticeable. Until then all I am asking you is please hold on until we update ChatControl.
