### ISSUE TITLE
1.16.4: How to give only 1 tag in formatting to op

### ISSUE THREAD

**Issue by Inxity** [kangarko/ChatControl-Pro#2187]
When I try your Ranked_Format in your wiki and when i am op it gives me every single tag 
![image](https://user-images.githubusercontent.com/61350916/101191589-eb79e680-366a-11eb-84bd-056a5334848f.png)

**Comment by BugabuseMe** [comment]
use sender_permission, here's my founder config for example:

in formatting.yml
################################################

  chat_founder:
    First_Part:
      Message: "{pl_prefix+}"
      Sender_Permission: "chatcontrol.groups.founder"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - ""
          - " &6&lmyserverbruh Network"
          - ""
          - "&e{player} is a &4Founder"
          - ""
    Second_Part:
      Sender_Permission: "chatcontrol.groups.founder"
      Message: "{player}"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Click here to send a PM to &c{player}"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/w {player} "
    Third_Part:
      Sender_Permission: "chatcontrol.groups.founder"
      Message: " &f{message}"

################################################

then in the config.yml in the "Groups:" section, set the founder group chat like this

    founder:
      Message_Delay: 0
      Command_Delay: 0
      Chat_Format: chat_founder

################################################

and last, give the founder the permissions:

"chatcontrol.group.*" NEGATIVE, important otherwise it won't work
"chatcontrol.groups.*" NEGATIVE, yes, both of them dunno why
"chatcontrol.group.founder" POSITIVE
"chatcontrol.groups.founder" POSITIVE

I don't know why but the op also requires the permission with the word "group" instead of only "groups", but that's how it work so it's ok I think, hope this helps you

**Comment by BugabuseMe** [comment]
update: it seems that github loves removing spacing, so here's a pastebin to the formatting.yml stuff: https://pastebin.com/RViA2LwT

**Comment by Inxity** [comment]
I'm gonna try it thank you.

**Comment by kangarko** [comment]
Just give yourself negative Sender_Permissions and you wont see the tags you lack permissions for

**Comment by Inxity** [comment]
@kangarko but what if i am op? does negative permissions that i give still work?

**Comment by kangarko** [comment]
Yes it will work even if you have OP
