### ISSUE TITLE
1.16.4 Range chat

### ISSUE THREAD

**Issue by EdyMeleon** [kangarko/ChatControl-Pro#2278]
How I can make the chat to be range chat in only one world?
![image](https://user-images.githubusercontent.com/67687618/116735671-8945c780-a9f7-11eb-8834-8c18fe1e1c79.png)

**Comment by EdyMeleon** [comment]
I have a skyblock server and I want when you are on your island to be able to speak only to the people that are on your island, the island radius is 300 blocks and I want to make a 300 blocks chat range but only in one world

**Comment by kangarko** [comment]
Sorry, I understand what you mean now.

You can give players either one of these two permissions (change {channel} to your actual channel name) when they are in another world so that then they can speak for the entire world, and the range only applies in your island world.

<img width="753" alt="Screenshot 2021-05-01 at 15 48 37" src="https://user-images.githubusercontent.com/1918426/116784500-d0ce6100-aa94-11eb-9100-290d3350cfe0.png">
