### ISSUE TITLE
1.16.4 additional help for issue#2278

### ISSUE THREAD

**Issue by EdyMeleon** [kangarko/ChatControl-Pro#2279]
Hey, sorry for opening another ticket but I really struggle setting up the range chat. I don't know what I need to do in channels.yml and formatting.yml.
![image](https://user-images.githubusercontent.com/67687618/116825065-31919280-ab96-11eb-89da-82fb46f8b090.png) 
![image](https://user-images.githubusercontent.com/67687618/116825075-3ce4be00-ab96-11eb-953c-5b7592fb67e1.png)

**Comment by kangarko** [comment]
Hey! Sorry for the delay, btw I read all tickets even closed ones so next time just comment below that :)

Here's one way: 

1. Ensure you're NOT using channels so that Enabled key is on false in channels.yml
2. Then set Enabled key to true in formatting.yml file as well as the Range.Enabled in that same file.
3. For ranged worlds, do not give players any permissions. For NON-ranged worlds, give them "chatcontrol.chat.overrideranged" permission. Chat in the non-ranged worlds will be in the entire world, whereas in the ranged worlds only in the Range.Distance value from formatting.yml

**Comment by kangarko** [comment]
Yeah just comment below if you need more help with this :)

**Comment by EdyMeleon** [comment]
I did everything but the chat is ranged in every world 
![image](https://user-images.githubusercontent.com/67687618/117579957-1bd41e00-b0fe-11eb-8150-625c2cc1f0a5.png)

**Comment by EdyMeleon** [comment]
![image](https://user-images.githubusercontent.com/67687618/117579983-41612780-b0fe-11eb-9858-78716691af7f.png)

**Comment by kangarko** [comment]
By ranged you mean it has the 100 blocks distance? Because the permission will make the distance infinite but players still won't see/write messages from/to other words, that is the limitation of our plugin.

**Comment by kangarko** [comment]
I understand, unfortunately that's not possible with ChatControl Pro right now. The permission will make the range not infinite, but only infinite within the same world.
