### ISSUE TITLE
Minecraft Version: 1.17.1 "Problem with colors in chat!"

### ISSUE THREAD

**Issue by 0D101** [kangarko/ChatControl-Pro#2361]
I created a command for the player to send the message directly to the global using /g (Message)
But when the player tries to use some color (&2Hello), the message does not go!
I've tried everything, and I don't know what else to do!

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
[ChatControlRed.zip](https://github.com/kangarko/ChatControl-Pro/files/7999143/ChatControlRed.zip)

**Comment by kangarko** [comment]
![Screenshot 2022-02-08 at 09 01 44](https://user-images.githubusercontent.com/1918426/152943433-1c2015ca-0f29-4c02-8f79-f9043ff6875b.png)
You have an error in your settings > remove the "global" value.

Then set Rules.Strip_Colors to false because the /g is a rule which removes your colors, it should fix it.
