### ISSUE TITLE
Towny - chatcontrol issue *bug*

### ISSUE THREAD

**Issue by Demonkid1112** [kangarko/ChatControl-Pro#257]
Well recently I had made a post about ChatControl /tell, /msg, /reply and such what are not working once I updated to 1.12 and you had brought up Towny. I closed the old thread and decided to test a few things. After a few test I'm about 80% 1.12 Minecraft, chat control 7.3.19, and towny 0.91.4.7 have some cross compatibility issues when it deals with private messages. Everything else seems to work perfectly fine, including admin chat. 

I'm not sure if this is feasible to fix on your end or if it is solely a towny thing in which we have to wait for them to fix it.

**Comment by kangarko** [comment]
Hello,

to avoid interference with other commands, we unregister /msg and /tell commands on startup and then register own replacements. This cannot be done when Towny is enabled, because it will disable its own command /t. I am sorry for the inconvenience, this is something I have been trying to work around but it is not possible when the user can customize the command aliases. For now it's a major incompatibility. I am sending you the relevant code below for an illustration how it works.

```
if (!HookManager.isTownyLoaded()) {
	CompatProvider.unregisterCommand("msg");
	CompatProvider.unregisterCommand("tell");
}

CompatProvider.unregisterCommand("r");
CompatProvider.unregisterCommand("reply");

Command.make("tell", Settings.PrivateMessages.TELL_ALIASES, new TellCommand());
Command.make("reply", Settings.PrivateMessages.REPLY_ALIASES, new ReplyCommand());
```
