### ISSUE TITLE
How do I make it so for each letter there is a star instead of just "****" everytime?

### ISSUE THREAD

**Issue by YepImRobbie** [kangarko/ChatControl-Pro#293]
1, l like this plugin a lot, and I'm curious as to how I can have it give the corresponding amount of stars to how many letters there were in the swear.

2. Also, how do I stop it from doing:
ORIGINAL MESSAGE: Hey, fuck you
What ChatControl do: Hey, ****you
What I want: Hey, **** you

ChatControlPro version 7.1.5

**Comment by kangarko** [comment]
Hey YepImRobbie & thank you for using ChatControl!

1. Currently you can only specify either 
a) replacement for the specific part of the message: Hello fuckers --> Hello [CENSORED]
b) replacement for the entire message: Hello fuckers --> I love this server!

A feature of your request is planned.

2. This is related to the filter, because it is "greedy" to increase the catch rate. You can insert \b at the end of the "fuck" filter (see rules/rules.txt) but then, it will be easier bypaseable if players say for example fuckkk (anything after "fuck")
