### ISSUE TITLE
@<player> feature not formatting properly

### ISSUE THREAD

**Issue by Tsuser1** [kangarko/ChatControl-Pro#303]
When players use the @<player> feature to notify another player, after the tag the chat is not returned to the proper color.

Example:
http://i.imgur.com/3E1XB2b.png

**Comment by kangarko** [comment]
Hello,

this is a know bug, because the chat event that we filter only include the message. You are most likely having the suffix that gives the gray color, which is included in chat format:

To illustrate:
Chat format: <prefix><player><suffix>: <message>

I am leaving this open for possible future workarounds.

**Comment by Tsuser1** [comment]
Would it be possible to have a configurable option to change the suffix color after the @<player> highlight so it could be 7 instead of f in this example?

**Comment by kangarko** [comment]
For now I'll rather look up a proper solution then this very limited workaround.

**Comment by kangarko** [comment]
Resolved in 7.5.0 :-)
