### ISSUE TITLE
Typo/slang correction not found?

### ISSUE THREAD

**Issue by MrBaconHawk** [kangarko/ChatControl-Pro#34]
I can't find a way to add in the typo/slang correction you were claiming this plugin has or can do.  Can you provide me a way to fix typos such as "teh" being changed to "the" or "u" being changed to "you".  etc. etc.?

**Comment by EvilOlaf** [comment]
Quite easy.

```
match teh
then replace the


match \bu\b
then replace you
```

And so on...

**Comment by MrBaconHawk** [comment]
Can I do this?

match \bgonna\b

then replace going to

Or is it an issue to do "Going to" with the space there?

**Comment by EvilOlaf** [comment]
Nope, should work.

**Comment by MrBaconHawk** [comment]
I'm going to have to add every single typo there is then manually?  That's going to take a million years.  Know of any shortcuts or ways to get a better list of typos that can be corrected?

**Comment by EvilOlaf** [comment]
Due to the design of the plugin you can very precisely define what to detect and what to replace with. 
However there is no feature like an auto-correct. This also would not be easy to make because either you would have to send the message to an online service to let it auto-correct, get it pack and send it then to the chat which would lead into delay or including dictionaries in various languages as well as grammar rules. Both would significantly increase server load, plugin size and probably the cost as well because commercial distribution of dictionaries needs to be paid ^^

To cut the  long story short: Yes you have to add each typo you want to have automatically fixed as a rule.

**Comment by MrBaconHawk** [comment]
Okay, well thanks anyway.

**Comment by EvilOlaf** [comment]
You're welcome.

Feel free to contribute to the project by sharing a few of your typo corrections as examples to let others benefit :)

**Comment by MrBaconHawk** [comment]
Oh, definitely.  I'll see if I can't get my developer to make a system that catches typos by cross-checking them (like you said, but instead, put it in a queue and do it when either nobody is online or CPU usage is low so it causes no troubles) and if it finds errors it makes new rules for them (perhaps I'll make it store the typo so it can be reviewed first before officially added as a rule, since I don't trust computers to do it correctly... lol).  Does that sound like it could work to get a good-sized list to share with everyone?

**Comment by EvilOlaf** [comment]
Sounds quite interesting. 
I am no developer of CHC, @kangarko might be interested though ;)

**Comment by MrBaconHawk** [comment]
Well if I can't seem to figure it out, I'll ask him if he wants to help.  It could make a huge difference in his plugin, and he could do a lot with that.
