### ISSUE TITLE
[7.5.0] Color don't work anymore

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#347]
i noticed colors stopped to work, chatcontrol keep to do this:
If i write &cRed it will output 266Red
If i write &4Test it will output 219Test
I am sure that is a bug

Thank you for the big update anyway

**Comment by LogGits** [comment]
I have noticed this aswell. The symbols are also printing double. e.g. <3 sends <3 <3. xion87 could you test this for me to see if you experience this aswell.

**Comment by xion87** [comment]
I confirm the issues with symbol, all are doubled

**Comment by kangarko** [comment]
Dear xion and LogGits,

I am on it. I apology for the issues. It has been a large update so somewhere in the code a bug or two may have appeared.

1) The color bug has been confirmed and fixed.
2) The double-symbol bug has been confirmed (caused by the new dynamic-replace system for swears, replacing fuuuck with as many *'s as the word length is, but also working unexpected here) and fixed. You must now insert `@prolong` in front of the one letter message to automatically prolong it.
