### ISSUE TITLE
Admin Chat

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#366]
Can you make /chc ach with no arguments do the switch? There isnt a need for the extra argument. "Chc ach" can toggle admin chat mode. Its a very simple thing that is more of a quality of life thing. it makes the command easier to user. It also makes it so i can use 1 alias to toggle and type in admin chat (e.g. i use /ac).

**Comment by kangarko** [comment]
Hello,

thank you for this suggestion. I have to reject it, because by ChatControl's logic, when a command is run without arguments, the help is displayed to the sender.

You can create /cc argument to run '/chc ach switch' either way, see https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands

**Comment by LogGits** [comment]
There is no need to have two commands to do one thing. You can specify what it does when they type /chc it shows something like "/chc ach <msg>" with the msg being optional. If its only "/chc ach" it will toggle admin chat. however anything more than "/chc ach" will be sent to adminchat.

"/chc ach hi" will print to adminchat.
"/chc ach" will toggle adminchat.

**Comment by kangarko** [comment]
Hey, I will keep it on the table, but for the minor releases it will remain as per the current system. Thank you for your understanding.
