### ISSUE TITLE
CHC containing backdoor

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#371]
Forcefully disabling CHC 7.4.24 from remote was not only probably the worst idea ever, it also offered that CHC obviously containing backdoors to control it from remote. Now THAT is something I would consider calling a security flaw.

Until the CHC/NPC issue is not solved we simple cannot update to 7.5. Therefore we now have to run the server without proper chat solution or shut our services down.

For now we have to search for an alternative chat solution which hopefully does not contain trojans and until this is solved I will also stop offering any help to others.

Best regards
Olaf

**Comment by kangarko** [comment]
Hey,

yes this was a mistake. I have immediately enabled it back again. The reason why I added the feature of where the plugin can disable itself was the following: Imagine I am on holidays without an access to the code, and suddenly a critical vulnerability is reported. **If** continual use of the plugin would render higher risk then **not** using it, then I would call the feature. AuthMe has a similar feature where it stops server if the authentication fails, protecting the users and staff members. I understand in this scenario it was not such severe so I have enabled it back again.

I had to delay the NCP issue in favor of other issues that were reported.

You can also read my statement at https://github.com/kangarko/ChatControl/issues/255.

**Comment by FrozenBeard** [comment]
For reference for everyone else, I also Spotted that the plugin contains a backdoor and was utterly outraged that a backdoor was included, especially in a premium plugin. I leave my server for 24 hours and come back after a restart and there are people swearing in my chat, posting URLS, I went into panic mode and thought there was a major issue. I had to pull my logs and scan to figure out what the hell you had done.

I think I was more worried that a backdoor was put in place to trigger remotely than than something breaking out of the blue.

https://www.spigotmc.org/threads/%E2%99%A3-chatcontrol-pro-1400-downloads-paid.82298/page-135#post-2673440

Why the HELL you wouldn't just send a message to OP's that log in/staff with a permission is utterly beyond me.

**Comment by kangarko** [comment]
To clarify the situation,

Firstly, I am aware of the fact that if your server relies heavily on ChatControl, just like mine did, plugin malfunctioning will render a risk and leaves your server in a default, vanilla-like state. No one wants that, and I would even considered a refund be it I am in your shoes.

The situation that happened was, that I tried to shutdown a leaked (and potentially dangerous) version of the version 7.4.24. Since the anti-piracy has been changed several times, and it is constantly changing, it happened accidentally that the plugin disabled itself to more users as it should. I sincerely apology for this very inconvenience, as my intentions were different (see below).

To ensure every user: The server to which ChatControl connects is secured. If the domain is unavailable, nothing happens. If invalid data are provided (in case of a ddos attack or certificate expiry), the plugin silences the error and continues loading. 

It _was_ only when the instruction explicitly and clearly stated that the very certain version should have been disabled, based off of the user identification string, which is unique to each buyer, and, resource id, which is unique to the .JAR file you download, that such should be issued. The anti-piracy instructions have been completely changed and the old version had interpreted it wrongly. Once again, I apology for that, and have removed that feature. 

It is all corrected now and you can safely run all versions of ChatControl listed in the Version History.
