### ISSUE TITLE
[7.5.3] Antispam and anticaps is broken

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#372]
I noticed with the new release ip like "mc lololololo com" (by using spaces instead dots, are not blocked and players can spam caps like "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA" but they can't do xDDDDDDD (the first letter is ignored from cap control)

also i tried the rules for avoid repeat and is not working:
**match (...)(?=\1\1+)
then replace**

**Comment by xion87** [comment]
config: https://hastebin.com/jibeyedaxi.php
handlers: https://hastebin.com/azenunuyer.bash
rules: https://hastebin.com/ajutiruwoc.rb

**Comment by kangarko** [comment]
Please try with 7.5.4 as it corrects this behaviour.

**Comment by xion87** [comment]
I tried to update to 7.54
anti-cap work fine now
antirepeat rule work fine
but people can still spam mc blablaba it

Also i noticed by using this release, it rollback the config like in old style and use ChatControl_Data instead Chatcontrol_....

**Comment by kangarko** [comment]
What is your MySQL configured to as under "MySQLP.Table_Prefix" ? It's 'ChatControl_' by default, so the table name will be ChatControl_Data. 

The version 7.5.4 did handled the case where the old table did not exist, hence the error. I will silence it in the next version.

**Comment by kangarko** [comment]
To increase range of the domain filter, find the "match ..." line for the domain filter in rules/rules.txt (by default, line 81), and replace it with:

`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,| )\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b`

Please note that since this filter also catches whitespace, it may impose more false catches.

**Comment by xion87** [comment]
ok, for that but i remember in old release the antispam was blocking default the spam domain with spaces, i don't know why it stoped to block these.
And about config layout? is normal that it become "urgly" again with 7.5.4 version?

**Comment by kangarko** [comment]
The 7.5.0-7.5.3 had the filter in an odd version, hence the weird behaviour. This has been corrected in 7.5.4.

The configuration is stripped of commentaries when it is updated automatically. There is nothing I can do about it because the YAML specification does not support saving comments. The only comment section I have control of, is the header.

You can view the defaults here on the wikipedia, whenever you need to.

I assume this is fixed, feel free to comment below if anything.
