### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#385]
Saw this randomly appear in console today. Only happened once.

The message that failed was 'wat?' and I can confirm it only showed up in console, the message was not present in game.

https://www.hastebin.com/ogicuwosab.md

**Comment by kangarko** [comment]
Thanks. I will get to it 3nd of October due to stay in the outlands.

**Comment by astirling** [comment]
I've been having similar issues since 7.5.8. When I revert back to 7.5.7 everything works fine.

Plugin loads with no errors
Joining channels works fine (can see this with /channel)
I can see Bungee connected chat from other servers
When trying to type in the joined channel nothing shows up in game but an errors shows up in console
When trying to send a message to a channel 'An unhandled error occured during executing the command.' message pops up in game chat and an error shows up in console.
Server is running latest paper spigot build 1220
I've updated essentialsx to the lastest snapshot build #23

[Server log](https://pastebin.com/BGmjvDEB) - This includes startup and errors from ChatControl Pro 7.5.10 (also seen in 7.5.8 and 7.5.9)
[Chatcontrol error log](https://pastebin.com/YK2ATZAX)

**Comment by LogGits** [comment]
I am getting the same issue as @astirling

**Comment by kangarko** [comment]
The errors have been resolved, I am sorry for not closing this sooner. Please let me know if anything else comes up.
