### ISSUE TITLE
Case insensitive does not work for Russian characters

### ISSUE THREAD

**Issue by Hdadaw** [kangarko/ChatControl-Pro#392]
I noticed this problem a year ago, but just now I decided to tell you about it.

Example rule in chat.txt
```
match ^(hello())$
then warn &eTest: $0

match ^(привет())$
then warn &eTest: $0
```
Result:
![image](https://user-images.githubusercontent.com/32250813/30924555-a9ed0bd0-a3e1-11e7-9c49-b50bd997c1a5.png)

**Comment by kangarko** [comment]
Hey,

thanks for noticing. I have also received one more message about this problem, but was not able to fix it. It seems like this is caused by the system's regular expression matching, which is outside of ChatControl's reach. We do have 'case insensitive' flag enabled for matching. I have noted this down and will take another look in the next major update.
