### ISSUE TITLE
Broadcaster not working properly

### ISSUE THREAD

**Issue by le0-minelandeu** [kangarko/ChatControl-Pro#414]
After 7.5.12 update, my auto messages got messed up. I don't know why, but the plugin cannot broadcast empty message (I use this to avoid using bold symbols and to have clear and nice chat)

[code](https://pastebin.com/6aztHwun)

![screenshot 2017-10-09 19 29 07](https://user-images.githubusercontent.com/31539367/31350846-f222ca02-ad28-11e7-9056-7f6409068663.png)

**Comment by kangarko** [comment]
Hey!

I cannot reproduce on 7.5.13. You can try setting &r&0 instead of &8, or some literal characters just to test how it will reproduce on your system. If you changed or updated other chat-related plugins (DeluxeChat, etc.), try to disable them temporarily to see if they cause the message to go away. Lastly, try to disable packet rules in ChatControl to see if it helps. 
![image](https://i.imgur.com/ETdjRpm.png)

**Comment by le0-minelandeu** [comment]
Okey, solved with using extra special character in "empty" line.
