### ISSUE TITLE
Couple of issues/suggestions

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#418]
Suggestion:
/chc ach - switches the channel. There is no need for an additional argument ("/chc ach switch" should be "/chc ach").

Issues:
For some reason my chat control doesn't censor correctly.
1. It doesn't detect when there is a letter in the way. E.g. "sheit" doesn't get censored but "sh1it" does.
2. The filter is doing that thing from a while back where it would censor to 5 characters. I am using `Replace_Word: "@prolong*"` shit is censored as ***** which is 5 characters long. B**ches is censored as ***** 5 characters again even though the word is 7 characters.

Match isnt working for another thing im using.
```
match \:welcome\:
require perm server.welcome
then replace &fWelcome to the server!
```
even thought i have the permission it doesnt replace it.

Also some guy cam on and advertised the equivelant of xxx.xxx.pro and it didnt stop him from advertising. Does anyone have a good swear filter regex that blocks majority of domain types that i could use?

On a side note when join the server it says this (The url is incorrect):
http://prntscr.com/gxjo45

**Comment by kangarko** [comment]
Hello!

**Suggestion**
The logic is show users what the command does - adding a function to play command here would cause confusion for some, so I have to compromise. No sorry.

**1.** Filter Not Working
Please check your filter. The default filter does not block "sheit". You can always add it to the filter if you wish.

**2.** Prolong Always 5 Letters
Correct. The `@prolong` feature has been paused due to issues, it is hardcoded to replace with 5 more letters each time.

**3.** Match Not Replacing
Are you talking about packet rules? Ensure you do not have the "chatcontrol.bypass.rules.X" permission otherwise you will get bypassed.

**4.** Incorrect URL
What part of the URL is incorrect?

**Comment by LogGits** [comment]
1) I was using shiet as an example for if shit was in the filter. They can also do shiyt but they can't do shi1t is there a way to block words even if character between it? Fkuck also works.

2) Ok thanks I thought my config was broken xD

3) no its a regular rule that replaces the text welcome with welcome to the server. It used to work before the update now it won't work. Even if they have perm server.welcome.

4) takes me to the resources page not ChatControl Pro

**Comment by kangarko** [comment]
1. You can just expand an existing rule as per [this](https://github.com/kangarko/ChatControl-Pro/wiki/Rules) article, and insert the blockage of "1" to shit to it.

3. Works for me -> I've put it in chat.txt. Try to comment out the 'require perm' operator just to be sure. Also, make sure you don't have chatcontrol.bypass.rules.XYZ permission otherwise you would get ignored.

**Comment by LogGits** [comment]
1) ok awesome
2) mine is in rules.txt. is it supposed to be in chat.txt?
Replacing :welcome:

**Comment by kangarko** [comment]
2. Technically not since rules.txt inherit chat, but you can try especially if you have other rules that may have caused interference of any kind.

**Comment by LogGits** [comment]
I think it could be because the account has all permissions. However, the account has the permission -chatcontrol.bypass.rules and -chatcontrol.bypass.rules.chat. Therefore, I am unsure as to what could be causing it. I moved it into the chat file and it still doesn't work for me. In addition to this it also doesn't allow me to use <3. The account is opped and has * permissions with the appropriate negated permissions.

**Comment by kangarko** [comment]
Try deopping yourself to see if it helps, eventually giving yourself negative `-chatcontrol.bypass.rules.*` permission as well.

**Comment by LogGits** [comment]
Ok a little progress with this, I guess its a small bug. These rules are located in the chat.txt file:
```match \:star\:\b
then replace ★

match <3\b
then replace ❤

match \:welcome\:\b
require perm server.welcome
then replace &fWelcome to the server!```
It appears to work when the player is opped and has the negated permission: 
`- -chatcontrol.bypass.rules.*`
It allows me to use the second rule in the chat.txt file <3. However, :star: does nothing and the :welcome: does nothing. When I test with negated permission `- -chatcontrol.bypass.rules.chat` it doesn't do anything.

**Comment by LogGits** [comment]
Resolved :)
