### ISSUE TITLE
BungeeControlBridge - Support placeholders & displaynames for server join/quit/switch messages.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#424]
Would it be possible to support player placeholders such as getting their vault group prefix / displaynames  for server join/quit/switch messages? It is something I heavily rely on with Essentials as it helps distinguish who is logging in when names are colored based on their grouping.

**Comment by kangarko** [comment]
Hello!

This is a really good idea, unfortunately there's no easy way to do this. I have tried to communicate back and forth with servers and Bungee, but this cannot be relied upon, especially since the player has left, there's no his reference in the server anymore. Without an obscure and unstable system this wouldn't be possible. But I have noted this down to the Future Roadmap in case anything shows up. Thank you for your understanding.

**Comment by mibby** [comment]
Would it not be possible to display quit/join messages the same way essentials does it? Still doing the display name lookup, just instead broadcasting it over bungee instead of localized server instance?

**Comment by kangarko** [comment]
Hey, it's not impossible. At the moment I am unfortunately busy doing another product launch, but I have noted that down for the next major release.

**Comment by mibby** [comment]
Ah, best of luck with that! Hopefully when you finish the new launch without too much issue, you could take a look. :) I'll just keep login/quit messages localized to individual servers for the time being with Essentials until / if it gets supported across BungeeCord globally.
