### ISSUE TITLE
Reloading chc breaks how many times messages get sent when sending messages cross servers.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#427]
With BungeeCord enabled, if you reload via ```/chc reload``` messages sent cross-servers begin to send multiple times. Each reload adds a new line for how many times the messages repeat. Breaks for both private messages cross-server and global chat cross-server messages.

**Comment by le0-minelandeu** [comment]
I have same issue, are you using Discord SRV with ChatControlPro or just ChatControl?

**Comment by mibby** [comment]
Just ChatControlPro.

**Comment by kangarko** [comment]
Hey!

Some time ago, I have made it possible to reload absolute every function in ChatControl.

Unfortunately this turned out to be problematic when it comes to console filter and bungeecords support.

I have resolved that problem by manually unregistering bungee channels just in the middle of a reload.

Thank you for your patience.
