### ISSUE TITLE
[7.6.8] chc reload broke all rules

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#468]
If you do /chc reload, people can spam and caps without being blocked by plugins, no errors. With normal start without using chc reload, all rules work fine.

**Comment by kangarko** [comment]
Confirmed. Seems like a bug in Spigot, because ChatControl unregister and re-register events we listen to, so, if you change Listener_Priority, it will take change upon reload.

I will revert this change and make listener_priority only change upon /reload or a full restart.

Have a great day/evening!
