### ISSUE TITLE
Updating ChatControl / Plugman

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#488]
Normally I updated chatcontrol with plugman. Since version 7.6.4, this is impossible. I now must upload a new version and reboot the server. I can't force an update with players online. So I upload a newer version and delete the old one and wait for the reboot to happen at scheduled time. Every plugins runs in memory so it should not be a problem. But not chatcontrol. When a player joins, the chatcontrol expect the jar file which is not found and creates lots of errors.
So how does chatcontrol expect us to keep up to date at this high update rate without annoying players and without using plugman? I can't keep doing this at night.

**Comment by FrankHeijden** [comment]
plugman works for me currently with the latest versions. However, plugman is not recommended for loading/reloading plugins when the server runs, so its not supported currently. 

Im currently using the latest version of plugman, i recommend updating it or redownload/reset the plugin and see if that helps.

**Comment by x1p** [comment]
Well I haven't tried it with latest version. But my guess is that my setup is a bit too complex to be started with plugman.

**Comment by kangarko** [comment]
Hey,

PlugMan should _de facto_ work but it does awful things to the plugin manager in bukkit, which we have no control over, resulting in duplicated instances etc. (lots of internal java stuff).

If there are errors afterwards, please post them all, I may look into them.

**Comment by x1p** [comment]
Warn set 'swear' doesn't exist as specified in     Handler {
        Name: 'swear'
etc etc

**Comment by kangarko** [comment]
I see, unfortunately PlugMan does awful things to the plugin loader, leaving many classes duplicated in memory and when they trace loaded parts in the plugin, it results in such errors. I would advise to avoid reloading by PlugMan at all, and rather updating on a weekly basis instead. The fast update rate is better for the majority of users because they can get their issues fixed sooner then having to wait week(s) for an update. I cannot please everyone and I had to choose a strategy that works best for most. It is generally safe to skip an update unless it contains HotFix or the Fix is specifically relevant for you.
