### ISSUE TITLE
Handler's links doesn't work

### ISSUE THREAD

**Issue by Heliosard** [kangarko/ChatControl-Pro#518]
ChatControl Pro: **7.6.18**
ProtocolLib: **4.3.0**
Server version: **CraftBukkit version git-TacoSpigot-"c2835dfc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)**

Normally, clicking on the link, this should create an interaction when nothing happens.
![image](https://user-images.githubusercontent.com/31409151/33664384-be05c150-da93-11e7-9d38-893b36e40717.png)

Handlers config: https://hastebin.com/gataxuroyu.scala

**Comment by kangarko** [comment]
Hey,

this seems like a rare issue that I cannot fix, because it is your Minecraft client who ultimately determines what links are clickable to it. I am sure it would work without ChatControl because we use own way via JSON to sends the interactive messages, but at the moment cannot be made clickable always.
