### ISSUE TITLE
Chatcontrol is not autoupdating custom messages with new strings

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#567]
I read on wiki the when there are new strings, the plugin should autoupdate the messages on locales folder, Instead it trow the error and not autoupdating the locale, autodisabling itself: https://hastebin.com/puwodehutu.md

**Comment by kangarko** [comment]
I am sorry, I accidentally misplaced that message in the wrong section of the Italian localization. I will correct that in the next update. I checked the autoupdate mechanism and otherwise it works as expected.

To fix it now, you can just copy and paste this to Private_Messages section in your localization/messages_it.yml file:

`   Cannot_Message_Self: '&cYou cannot message yourself.'`
