### ISSUE TITLE
Issue with channel autojoins

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#586]
**Version (Command /version ran from console):**
`> [19:06:57 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
`> [19:06:57 INFO]: Checking version, please wait...`
`> [19:06:58 INFO]: You are 893 version(s) behind`

**When does the bug occur?**
Well, when a user joins the server with the autojoin permission node they are not automatically joining the channel I want.

**Are there any error logs?**
No

**Upload possible settings.yml sections that could cause the error:**
There are none

**Extra Notes**
I went for support in discord server and was told to make an issue here by one of the moderators, there was apparently another user having the same problem as well.

**Comment by kangarko** [comment]
Hello,

I assume this is a problem related to: https://github.com/kangarko/ChatControl-Pro/issues/577

I am currently out of country because I am moving away and it's difficult to look at it until 15th+ February (+ about 5 days). I am sorry for this and I am looking for a quicker solution. 

You can find a quick fix in the issue above using a automatic script.
