### ISSUE TITLE
CAPS lock feature

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#592]
Because I find the caps lock warning a bit to aggressive, I removed the warning. Since all too many uppercase characters are diminished, I find it too annoying. But I do like to have a warning if (nearly) all characters are caps locked. Is it possible to make it more configurable?

Something like:
"Caps lock warning if above (percentage): 99

Further more I am interested if it is possible to correct a mistyped uppercase if the second character is mistakenly uppercase if the rest is not (without changing the rest of the caps spam options)
eg: THis is an example message.

**Comment by kangarko** [comment]
Hello,

for the first suggestion, I compared the system with most anticaps plugins and it's pretty configurable - we have the option for caps in the row, minimum message length, total caps percentage and others.

So, you only want to display the warning message if the caps is above a certain percentage? That would be possible.

For your second inquiry, if you make a regular expression in rules/chat.txt folder for that, it will work, otherwise I don't know about a way of implementing it.

**Comment by x1p** [comment]
> For your second inquiry, if you make a regular expression in rules/chat.txt folder for that, it will work, otherwise I don't know about a way of implementing it.
Solved

> So, you only want to display the warning message if the caps is above a certain percentage? That would be possible.
Yes please

**Comment by kangarko** [comment]
Okay I will get to it 15th or 19th February ;)

**Comment by kangarko** [comment]
Added. A new release will be published 15/16th.
