### ISSUE TITLE
Chatcontrol Pro 7.7.3 - not work send private message bungee connected servers

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#618]
Agronaout online on bungeecord connected server and the Chatcontrol sent to wrong player.
This work perfectly on old Chatcontrol Pro 7.6.34

![36934883-5afe4d74-1ef0-11e8-851c-1d735932bd00](https://user-images.githubusercontent.com/8324198/36977148-77b2bfc2-2080-11e8-8034-8e3866bec361.png)

![36934885-5f6895c2-1ef0-11e8-82e4-d5e69e502c26](https://user-images.githubusercontent.com/8324198/36977164-846c69a2-2080-11e8-8958-d0a6b880ec42.png)

**Comment by kangarko** [comment]
Does it happen all the time or only once?

Sorry I cannot read the situation.. You send a message to "agronaut" that is on a different server, but "LOLO" received it, and he is on the same server as you are?

**Comment by poma123** [comment]
Yes, LOLO is on the same server as the message sender is, and agronaut is on a different bungee server, but not agronaut receive the message, but LOLO.

**Comment by poma123** [comment]
Almost. LOLO is on the same server as the message sender is, and agronaut is on a different bungee server. But! Not agronaut receive the message, but Goody!, who is on the same server as the message sender too.

Címzett: Goody = To: Goody

**Comment by c0wg0d** [comment]
I recently updated from 7.6.15 to 7.7.4 and I am having issues with PM's going to random players as well, or not being sent at all.  We are also using BungeeCord.  This is concerning.

**Comment by kangarko** [comment]
After investigating it may be that we resolve partial matches, e.g. kan finds kangarko. That may lead to such. I will do more research today.

**Comment by kangarko** [comment]
Issue addressed. Unfortunately it was a rather large fix that, together with the massive feature update in the nextversion, cannot be easily backported to the old source. 

Theory: We perform advanced checks to allow to find players easily by partial matches (e.g. "arko" finds "kangarko"). This check however does not assume that there is Bungeecord present, and so, when the receiver is on another server, it just pulls a player from the same server with the highest match ratio, who can be a totally different player.

New version will be therefore available in 1-2 days instead of an hour as a hotfix would take.

I advise to disable PM's in ChatControl and let Essentials or similar handle it until them. I personally apology for that.

**Comment by kangarko** [comment]
Fixed.

If at any point, problems arise again, please set Debug to ["pm"] in the next release.
