### ISSUE TITLE
🎈 Roadmap for Ideas and Suggestions

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#625]
![roadmap](https://i.imgur.com/a3FOfvL.png)
<h3><p align="center">A List of Ideas and Suggested Features</p></h3>

_Due to small team and high demand on us we are at present not open for more features. There is no ETA. All features are consideration only._

Merged into https://www.mindmeister.com/1589858477?t=3V2HKfCGzw

**Comment by kangarko** [comment]
Lots of features were added in 7.8.30 and 7.9.0 beta, but many had to be postponed due to works on [SpigotCourse](http://www.spigotcourse.org). Thank you for your patience.

**Comment by JarlPenguin** [comment]
Is native support for 1.13 already implemented?

**Comment by gelsbern** [comment]
Would it be possible to have the Discord channel messages go into the actual channels even when a player is offline rather than the generic [Discord] thin?  I have about 10 channels set up, and when a player goes off line and chat in Discord it all goes to the generic [Discord] channel making things very difficult to follow.

**Comment by kangarko** [comment]
I can leave that off as a suggestion, however I cannot give you an estimate as to when we will get to it.

**Comment by kangarko** [comment]
Looking for volunteers! If you believe you can help implement any of these features send me a brief introduction along with your code samples at matej@matejpacan.com

**Comment by Sikatsu** [comment]
''BungeeCord: Broadcast when player joined the network for the first time.''

I really hope you can add this one sooner then later. It looks quite bad currently that there is a join message either per server or not at all.

**Comment by kangarko** [comment]
@lackoSK @JavaFactoryDev may you please look into it? This should be able to be done on the 
BungeeControl plugin. Thanks.

**Comment by JavaFactoryDev** [comment]
I can only say one thing: There are great things coming up, soon:)

**Comment by Sikatsu** [comment]
Alright, well i'll hope it will be added soon, quite annoying how it currently is per-server. Offer still stands. ^^

**Comment by kangarko** [comment]
@lackoSK may you please look into this?

**Comment by lackoSK** [comment]
> ''BungeeCord: Broadcast when player joined the network for the first time.''
I really hope you can add this one sooner then later. It looks quite bad currently that there is a join message either per server or not at all.
No volunteers who would like to work on this one? Will be willing to pay 10$ for it.

You will be able to download it in the next update!

**Comment by JavaFactoryDev** [comment]
We have written few things that make this possible very easy:)

**Comment by Sikatsu** [comment]
Because I was unsure when this would be added, eventually someone on Spigot made a plugin that does that job. Will look into BungeeControl's option soon!

**Comment by Sotlol1** [comment]
Nicknames have been on this list for 3 years. Since many have moved on from Essentials isn't it time to consider nicknames?

**Comment by Sikatsu** [comment]
Was hoping for that as well. With MySQL support for bungee networks.

**Comment by lackoSK** [comment]
Hey there guys!

Nicknames **will** be implemented! Don't worry.

**Comment by kangarko** [comment]
Decided to reopen for now. Keep in mind we are still a small team so I cannot add all of those features effectively, but I will prioritize the most requested ones.

**Comment by Sikatsu** [comment]
#988 from the roadmap can be set as done since you added this in the latest update

And the ''RGB colors not parsing in mcmmo spy'' that is set for 9.1.0, I believe this is the same issue we are currently discussing in #1795

**Comment by kangarko** [comment]
The list cleaned, new ChatControl 9.1.0 is in development!

**Comment by kangarko** [comment]
Mindmap: https://mm.tt/1589858477?t=3V2HKfCGzw

**Comment by james-d-elliott** [comment]
I think some key point to be added are:

* making sure nicknames/data like the players first join time (for newbie messages) being stored in SQL (for networks)
* bungee AND velocity support (VelocityControl has a nice ring to it too!), I don't think there is any chat plugin that supports both of these, I also think velocity is the future of MC proxies, it's getting really mature
* consideration of ditching all "special" channels (adminchat, bungeechat), and just make them example channels to simplify configuration, I don't know if there is some specific benefit to them over normal channels but from what I can tell you can do everything with just channels.

**Comment by kangarko** [comment]
Thanks @james-d-elliott 

I would not ditch admin and bungee chat, because those can exist even if channels are disabled, it is like a layer above channels

**Comment by kangarko** [comment]
@james-d-elliott good news, I've added nickname store both flatfile & db, and simplified channels, as you suggested.

No velocity. I simply don't have the resources to do that right now.

**Comment by james-d-elliott** [comment]
Nice, the DB support is perfect for networks. I'm not overly worried about Velocity, but it would give you access to users in that community, I also do not believe there are any current chat plugins that support both BungeeCord and Velocity, which would give people a smooth transition. I personally want to transition to Velocity at some stage, and looks like there are at least a couple other CCP users that want to. 

So if I were in your shoes (and not trying to be pushy) keeping in mind I don't fully understand java or the BungeeCord communication process:

* Make sure the communication between ChatControl and BungeeControl is abstracted via an interface so adding the new communication classes later is not difficult (I'm just guessing you can use classes to communicate, hoping you can replace that with an interface). 
* Release 9.1.0 with BungeeCord support.
* Leave a month or so to squash any bugs (after the release).
* Start figuring out Velocity support. (would not guarantee anything)

**Comment by kangarko** [comment]
Is there any benefit besides the "trend" factor? Like a real measurable result?

**Comment by AngellitoX** [comment]
It's not precisely a trend, but more of a new platform that it's becoming real popular and the main basis of new servers. I'd say that adding compatibility to Velocity can significantly increase sales as you would most likely be the first chat plugin for that software, so there's a huge win there waiting for you man :)

**Comment by kangarko** [comment]
Yeah so that's exactly a characteristic of a trend ;) With my current capacity right now the best I can give it will be by the end of this year if more and more people will keep requesting it.

**Comment by Mohamad82Bz** [comment]
I have an idea for Sound_Notify feature.
In Settings.yml we have Use_Sender_Group_Color: true. 
It will be really nice if we can set a permission for sound notify color. For Example If I give `chatcontrol.soundnotify.dark_red` to one player, whenever that player says a name, that notify will be dark_red. Exactly like Use_Sender_Group_Color option but with permission, not picking the group color.
(This is a reverse mode of Sound_Notify_Color option)

Sorry if I explained bad.

**Comment by kangarko** [comment]
Thanks, you can use Groups option Sound_Notify_Color for this already: https://github.com/kangarko/ChatControl-Pro/wiki/Groups#sound_notify_color

**Comment by james-d-elliott** [comment]
I have thought about the question as to if it's a trend or not. Realistically all things like this are trends, including BungeeCord. I think what you mean is it's just a "current fad" or "passing fad". There are reasons that have convinced me this is not the case, maybe they will convince you too: 

1. Highly used plugins offer support for it:
  * LuckPerms
  * TAB
2. The primary maintainer actively ports or helps port BungeeCord plugins to it.
3. The project has been around for quite some time.
4. The Velocity Discord has ~400 users. 
5. There are 29 contributors to the project (including 5 people with more than 1000 lines of pure additions).
  * For contrast BungeeCord has 122 contributors with only 4 of them being over 1000 lines of pure additions.

Regarding the benefits as far as I understand them they are as follows:

1. Less resource usage per client due to a more modern design approach.
2. It focuses on purely being a proxy and doesn't interfere with things like scoreboards.
3. In-built "BungeeGuard" (server validates proxy and does not allow direct connections even when a user configures their firewall incorrectly).

**Comment by KasearMC** [comment]
mcMMO party chat hook (and Lands)

please add the option for CCP to hook into mcMMO's party chat to take it over. i want CCP to handle all of the chatting on my server but it is also necessary for players to be able to use party chat when they join a party.

this is exclusively beneficial for everyone since many servers run CCP and mcMMO together.
the problem is that the mcMMO party chat does not have the formatting, features, and control that CCP has.

____________________________

same with the Lands plugin... i was going to make a separate post for this but i would essentially be typing the same thing, swapping "mcMMO" with "Lands" and "party" with "land".

**Comment by kangarko** [comment]
Thanks, will implement that.

**Comment by kangarko** [comment]
Closing, we're now finished with ChatControl 9 and moving into the final testing phase
