### ISSUE TITLE
Channel handling

### ISSUE THREAD

**Issue by skyybender** [kangarko/ChatControl-Pro#629]
Hey kangarko,

we bought the ChatControl-Pro plugin some days ago (used hero-chat before) and we have a lot of trouble with the channels function. Honestly I don't understand the concept of the channel read/write function.

We created several channels in the channels configuration. Then we created the chat-formats in the formatting.yml and linked it with the channels. This worked fine except of there is no posibility to use the display-name of the player as a chat prefix. Maybe you can add this as a placeholder (something like {dplayer}).

Now I want to join one channel and write some message. Until now everything works fine. Now I want to write somethin in another channel. Here I need to use the switch command, which removes me from the previous channel. Is there any way to stay in the previous channel and switch to read mode? This way I need to leave the first channel, join the second one and then join the first one with read mode again. I don't know any user that will understand this process.

One more weird thing: If I'm in channel one with read mode and in channel two with write mode, I am not allowed to switch from channel two to channel one. I need to leave channel one and join it again with write mode. Is there any concept behind this way of using channels, I do not understand?

At least, is there any way to allow users writing in only one channel at same time? You can allow users joining only one channel at once but it is not possible to stay in other channels in read-mode.

One more thing that should be changed: If the console sents a message to a player, it is getting formated like it is a private message. Maybe you can add one more format for console->player messages.

Thank you :)

**Comment by kangarko** [comment]
Hello and thank you for your purchase.

We have a display name variables, see https://github.com/kangarko/ChatControl-Pro/wiki/Variables.

You can be in a multiple channels at once, but sending any chat message will be sent to both of them. You can use "/channel send" command and make an alias (https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands) like /ach to send a message to another channel directly.

Yes, because the "switch" takes into account any channel mode. You are in the channel per say, just the mode is different.

Yes, you can force users auto-join a channel with the read or spy autojoin permission on login, while keeping them writing in the major channel (https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join).

I am currently not planning to add feature updates very soon due to other priorities, but I will keep this in mind. Thank you.

**Comment by skyybender** [comment]
Thank you for the answers to my questions!

Unfortunately telling the players to use the "/ch send" command will not be an option. I have problems to understand the usage of sending messages in multiple channels but I accept that it simply is a different concept. The auto-join permissions are not that usefull for me when it is not possible to switch the channel-mode (read/write) with one single command.

One last question to this toppic: Is there any chance to get an API-Function for changing the channel-mode for players or to force-join them to single channels silently? This would bring the possibility to create the commands I require by myself. If this is not an option the plugin unfortunately will not fit to my server-concept at all.

Thanks for your help :)

**Comment by kangarko** [comment]
To make it more simple you can create one command like /shout or /sh using command aliases (see the Wikipedia).

Also, /chc ach and /chc g support the "switch" argument at the end, which makes them temporarily permanent, just to keep in mind.

Yes, I believe you can achieve this with the current API. I included its raw version here (please compile against the full version not this).

**Comment by kangarko** [comment]
Closing to clean up the issues page, if you have any more questions please post below, I will read it!

**Comment by skyybender** [comment]
yeah no problem, I wrote a smal workaround that makes ChatControl work like I prefer. If you want to add some parts of my code to the plugin, just tell me and I will send it to you.

Would be great if you add the "message-from-console" formatter to the plugin like I wrote below. It wasn't possible to write a working condition (like "{sender}" == "CONSOLE") so I have to wait for your implementation.

Thanks for your support!

**Comment by kangarko** [comment]
Awesome, yes, you can freely post how you made it and I can either add it to plugin or to the Wikipedia.

Anyways, I tested that condition and it should be working, but what I found rather confuses me. All seems okay, even the console output, but it seems that I cannot get it working in Javascript. Maybe you can have a look, otherwise I am afraid I cannot help you with that:

![a](https://i.imgur.com/vdRUjp5.png)

**Comment by skyybender** [comment]
Right here my "smal" implementation:   
Code (one single listener-class): https://hastebin.com/ruyawukofo.cs   
Config: https://hastebin.com/akenawoqow.pl   

Not the best solution, I know, but with this listener you are able to   
- define aliases for any channel name   
- define channels that are getting joined by default when you don't have any others selected (different from autojoin-permission)   
- define a configurable help message when you type a invalid command/channel   
- allow users to join channels with one single command that switches all channels to read mode and the given one to write mode   

It is a bit hacky but I found no other solution for handling the channel join process, as your ChannelSwitch event does only get thrown on successfull channel-switch (not if user is already in the channel with read-mode or things like that...). Feel free to use the code for your plugin!

To your question below: Honestly I don't know what you are doing with javascript here. The javascript part of your wiki is a bit confusing and I'm not sure what you want to achieve with it. Seems like checking for console-sender simply doesn't work. Maybe you can add a field (like ConsoleMessage: true) to the formatting.yml channels section that works like the condition you try to build below.
