### ISSUE TITLE
ChatControl v. 7.8.2 | Problem

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#662]
Hi, I have Just installed the Lastest version of ChatControl on my server, But the plugin give me this Error:
https://pastebin.com/TicbnjBk

**Comment by xion87** [comment]
Same

**Comment by BlackGamer000** [comment]
Same Error: https://pastebin.com/MeWVMi2B 

:c

**Comment by Fonzee9** [comment]
Same issue! here is my log of com9
https://pastebin.com/SCKs2S9C

**Comment by zeronerve** [comment]
Same....
https://pastebin.com/sCT1fgvi

**Comment by kangarko** [comment]
Will be fixed in an instant. I am terribly sorry for the mistake of uploading the jar from obfuscator that produced that error, instead of the one from test server where I test all builds. There is absolutely nothing wrong with your server, I made the mistake and uploaded a version of file that is locked to my computer only. This is now corrected.

**Comment by FedericoGB25** [comment]
Thank you very much! :)
