### ISSUE TITLE
[7.8.7] Chatcontrol will stuck the server sometimes

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#695]
https://hastebin.com/izopecocof.md

on errors.logs
https://hastebin.com/eponidomaz.vbs

error during  normal server atitivity
https://hastebin.com/icilipaqeb.sql

**Comment by xion87** [comment]
I add also a crash here https://hastebin.com/pawonebeji.md

**Comment by kangarko** [comment]
Hey, thanks for the last report. ChatControl doesn't create infinite threads because there is no such code. There is a single repeating thread, a task broadcasting timed messages.

I suspect it has something to do with the players' cache, perhaps it's getting too big. What's the average of your players online? Do you know how many players join the server a day on average?

The next version introduces a new debug option. Please set your Debug to "cache", and every two minutes a message will be printed about it. If the crash happens again please post me the last debug message. Thank you.

**Comment by xion87** [comment]
I haved like 40000 threads opened, downgrading chatcontrol to 7.8.6 fixed the issue

**Comment by kangarko** [comment]
I have solved the stack overflow error, please re-test on the next version for the "value already in the list one" and the freezing.

Also, do you have the reset cache on quit option enabled?

**Comment by kangarko** [comment]
I have edited my post above in case you missed the edit ;)

**Comment by xion87** [comment]
- i have only Reset_Cache_On_Quit: true on my hub... i will enable that on all my server
- i have an averange of 300-400 players online
- i will try to debug (if you want i can jvm analyze so i can send to you all details)

**Comment by kangarko** [comment]
I further updated the player cache to have expiration of 1 hour (when player logs off and does not join for 1 hour his history (for antispam and antibot) is cleared).

I am closing in faith that this definitely solves the problem. If not, please comment below and include the JVM analysis so I can see what object (List, Map, ..) causes most memory consumption. 

Thank you for your patience.
