### ISSUE TITLE
[7.8.11] Chatcontrol crash server 

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#732]
Here my server random crashed (120 players)
https://hastebin.com/oliwanacuc.md

**Comment by kangarko** [comment]
I apology for the inconvenience, I am on it.

How big is your data.db file just for the record?

**Comment by x1p** [comment]
?
```
MelyForEver_ issued server command: //hsphere command 10000
MelyForEver_ issued server command: //confirm
```

**Comment by kangarko** [comment]
Excellent catch @x1p,

@xion87, it may be caused by the huge WorldEdit operation.

ChatControl has "synchronized" methods that will display in the stack trace even when they are not a direct cause. I have optimized some blocks of them in the next version.

If it happens again, still please post an issue.
