### ISSUE TITLE
chatcontrol.spy.autoenable

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#740]
This permission seems to be being ignored again.  It's about every other time I login, it forgets I have it or something.  I know the release put out TODAY dealt with something in regards to this.  Whatever you did with this past release basically dropped ChatControl off my timings list completely, so it is working a ton better, but for some reason it's still not always applying /spy to users who have this permission.

**Comment by kangarko** [comment]
Thanks for reporting. Yes, please stick to the latest release as the fix is quite severe. I apology for the inconvenience.

Set Debug to "[spying]" in the next release, and it will print out additional console information.

Finally, next versions should solve this. Problem was, that the MySQL is loaded asynchronously, so it was loaded after auto-spy, so it could set the /spy back to disabled.

**Comment by mrcoffee1026** [comment]
ah ok.  Might explain why SOMETIMES it seemed to use the permission and SOMETIMES not, I couldn't sort out any pattern for my "current status" though.  Thanks again.
