### ISSUE TITLE
Chat messages not sent to Discord

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#778]
So I've installed DiscordSRV along side ChatControl and I'm having trouble getting the chat messages to appear from the server to Discord.

- I'm not running any other chat handlers other than ChatControl.
- It is a BungeeCord setup, with DiscordSRV running on the Lobby.
- The connection from DiscordSRV to Discord works as I can see join/quit/achievement messages in the proper channels on Discord. 
- I am able to send a message to the admin channel via the console and that also appears in the appropriate channel on Discord. However when I send a message to the admin channel from either the Lobby server or any of the BungeeCord connected servers my messages (nor any of my other admins) do not appear in Discord.
- I have connected my Minecraft UUID to Discord, in case that was the issue. It was not. 

I'm hoping you could take a look at my config and see if there is something I'm overlooking. 
If there is any additional information I need to provide, let me know and I'll be happy to do so. I appreciate your time. 

[ChatControl - Copy.zip](https://github.com/kangarko/ChatControl-Pro/files/2107626/ChatControl.-.Copy.zip)

**Comment by kangarko** [comment]
Hello,

Thank you for posting ChatControl folder, it looks fine!

Please also send me your config.yml file from DiscordSRV (make sure to remove BotToken).

Sincerely,
kangakro

**Comment by kangarko** [comment]
@Kolgrath, I apology for a big delay this time (normally the support is much faster but I was out of workspace).

When I join with your setup and type, the message is not send to the admin channel regardless of whether I am joined in that channel via /ch join admin or not. This is because you have Bungee_Chat.Enabled_By_Default on true and so I am joined to the global chat instead.

When I toggled that off with /chc g switch and then joined /ch j admin, I was able to send message to admin channel and they appeared on Discord as well.

Please note I am talking about "admin" channel and not "adminchan" you have there.

Lastly, you set Channels.Your_Channels in localization to none. This is wrong since it will break the channel info in /channel command. If this is desired by you, you can leave this. Otherwise, remove the key and a new fill appear.
