### ISSUE TITLE
Nothing working? (ChatControl Pro)

### ISSUE THREAD

**Issue by Lakebighead** [kangarko/ChatControl-Pro#877]
Chatcontrol Pro isn't letting me use the commands and it's not blocking any swear words. Pretty much not working at all. It is on the latest version. Nothing in the console besides ChatControl starting up or being disabled when I reload or start up the server.

Edit: Found some errors: https://pastebin.com/ZhRBHEYz

**Comment by Rbot48** [comment]
The error is telling you that one of your rules has an incorrect formatting. The regular expression is lacking a `)` at the end. It should be `\b(f+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_))` instead of `\b(f+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)`.

You can use websites like https://regex101.com/ to validate the syntax.

**Comment by kangarko** [comment]
Your rule containing

> \b(f+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)

has malformed syntax, hence preventing plugin from loading. As Rbot48 mentioned, you need to fix that rule first so the plugin can load correctly.
