### ISSUE TITLE
Packet rules are severely outdated/limited.

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Pro#885]
I'm using these rules for a few reasons:
- To rewrite the messages of a plugin, e.g no permission messages (Much easier to use regex to modify these rather than going through every file to change this. Most lack the option to even change it), plugins that have messages that can't be configured, etc.
- To rewrite the response of a plugin, e.g essentials help (specifically hiding plugins names being responded, an example of this would be `/help <plugin name>` returning `Commands from <plugin name>` if the plugin is present on the server, I'm using it to rewrite that message to the nothing matched response which looks a little something like `Commands matching "<search term>"`

However, my players recently discovered they can just say these messages in chat and trigger the rules and it's become quite a nuisance for both myself and my players. Is there anything that can be done about this? It seems I have no other option other than to use this seemingly outdated ruleset.

**Comment by kangarko** [comment]
Hello,

the rule system is actually fairly new and kept with the latest standards, but since MC 1.7.10 each message is sent as a chat component. A simple message like "&8! &cDo not repeat this command" is split into something like this:

![a](https://i.imgur.com/zARnSrN.png)

That's why, ChatControl must evaluate each part of the "text" component manually (if we would put it into one, it is not possible to convert it again without loosing some of the formatting). That's why, it has absolutely no idea whether a player sent the message, or a plugin.

I am sorry but there is little I can do about this.

After my testing it seems that prepending a rule with ^ is not matched when sent by a player:
![a](https://i.imgur.com/7pqRUM6.png)

You can experiment with it and make your rules as narrow as possible to minimize false catches.

**Comment by ArtelGG** [comment]
I think if you're just matching something you could easily strip the colour similar to what is done with every other ruleset, sending a message back might be a different story though.

**Comment by kangarko** [comment]
Exactly - I can strip the color and put the messages together, but that would break "then rewrite" because we would need to put the message back together which is very challenging with the current system.
