### ISSUE TITLE
reguarding Command.txt issue

### ISSUE THREAD

**Issue by Chris4418** [kangarko/ChatControl-Pro#91]
apologises for another one. I removed the colons, that did nothing to fix the problem. I deleted the .txt file in the hope that the plugin would regenerate it. it didn't so i tried to re-install the plugin itself, it didn't regenerate the file even after a reinstall. could there be an issue with the plugin itself causing this problem as i have also noticed that the plugin was working before i updated it?

**Comment by kangarko** [comment]
_Continuation of https://github.com/kangarko/ChatControl-Pro/issues/88_

Like I said before, the files are okay. You cannot use the YAML parser, because that is only for files ending with .yml having yaml language. Those files have their own language and syntax. The color (:) is accepted as well.

If the file was not re-created, then there is some error in the console or you have command rules disabled (Rules.Check_Commands). Check the startup log for errors.

**Comment by kangarko** [comment]
Closing. Feel free to reopen or create new if you have any inquiries.
